<?xml version="1.0" encoding="utf-8"?><Database Name="Sakif" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.0.2;Initial Catalog=Sakif;User ID=sa" SettingsObjectName="Orders.Properties.Settings" SettingsPropertyName="SakifConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.clientes" Member="clientes">
    <Type Name="cliente">
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cliente" Member="cliente1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_01" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="apellido_02" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="tipo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="zona" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_de_identificacion" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Decimal" DbType="Decimal(4,0) NOT NULL" CanBeNull="false" />
      <Column Name="provincia" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="canton" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="distrito" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="Barrio" Type="System.String" DbType="VarChar(2)" CanBeNull="true" />
      <Column Name="identificacion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="telefono_01" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono_02" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="telefono_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="representante" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="limite_de_credito" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="descuento_general" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="dias_plazo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="creado_por" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="creado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modificado_por" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="modificado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="vendedor" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="acepta_impuesto" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="observaciones" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="mostrar_obs_fact" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="compania" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="animo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="correo_actualizado_por" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="correo_actualizado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="correo_anterior" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="CedulaCorrecta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="venta_mes_anterior" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="saldo_vendido" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="cliente_factura" Member="facturas" ThisKey="cliente1" OtherKey="cliente" Type="factura" />
    </Type>
  </Table>
  <Table Name="dbo.facturas_encabezado" Member="facturas">
    <Type Name="factura">
      <Column Name="compania" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="factura" Member="num_orden" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tipo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="cliente" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="cobrador" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="vendedor" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bodega" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="tipo_orden" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="referencia_cliente" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Cierre" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CierreMensual" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="meses_plazo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="CierreDiario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="referencia" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="zona" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="estado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="transporte" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_vencimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechadePago" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="fecha_ultimo_pago" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="subtotal_con_impuesto" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="subtotal_sin_impuesto" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="total_impuesto_ventas" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="total_impuesto_consumo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="total_monto_comision" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_descuento_factura" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_descuento_global" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_descuento_monto" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_intereses_por_mora" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="saldo_intereses_por_mora" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="linea1" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_bruto" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_total" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="saldo_factura" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="tipo_de_pago" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Column Name="porcentaje_impuesto_ventas" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="porcentaje_descuento_factura" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="porcentaje_descuento_global" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="porcentaje_comision" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="porcentaje_comision2" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="porcentaje_intereses" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="porcentaje_comision_lider" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_cupon" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="handing" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="monto_transporte" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="anulacion_salida_por" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mercancia_salida" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_salida_mercancia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="despachado_por" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="recargo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(4000)" CanBeNull="true" />
      <Column Name="estado_entrega" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="forma_despacho" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="enviar_a" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="creado_por" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="creado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modificado_por" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="modificado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estado_cobro" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cupon" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="prioridad" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="descripcion_factura" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="monto_bruto_real" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="cierre_inventario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="dias_atrasada" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PrimeraCuota" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="CuotaMensual" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="OrdenOriginal" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="SolicitaEstudio" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="MontoEntregaInmediata" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="postventa" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="plan_mercadeo" Type="System.Decimal" DbType="Decimal(2,0)" CanBeNull="true" />
      <Column Name="Verificada" Type="System.Decimal" DbType="Decimal(1,0)" CanBeNull="true" />
      <Column Name="consecutivo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CierreCreacion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MontoLocalizacion" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="deduccion_tarjeta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="actualizada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="insertada" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ref" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EntregaInmediata" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reclasificacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CuotasReclasificacion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="cliente_factura" Member="cliente1" ThisKey="cliente" OtherKey="cliente1" Type="cliente" IsForeignKey="true" />
    </Type>
  </Table>
</Database>