#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sakif")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Insertfactura(factura instance);
    partial void Updatefactura(factura instance);
    partial void Deletefactura(factura instance);
    #endregion
		
		public dbDataContext() : 
				base(global::Orders.Properties.Settings.Default.SakifConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<factura> facturas
		{
			get
			{
				return this.GetTable<factura>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _cliente1;
		
		private string _nombre;
		
		private string _apellido_01;
		
		private string _apellido_02;
		
		private decimal _tipo;
		
		private string _zona;
		
		private string _tipo_de_identificacion;
		
		private decimal _estado;
		
		private string _provincia;
		
		private string _canton;
		
		private string _distrito;
		
		private string _Barrio;
		
		private string _identificacion;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private string _direccion;
		
		private string _telefono_01;
		
		private string _telefono_02;
		
		private string _telefono_03;
		
		private string _fax;
		
		private string _email;
		
		private string _representante;
		
		private System.Nullable<decimal> _limite_de_credito;
		
		private System.Nullable<decimal> _descuento_general;
		
		private System.Nullable<decimal> _dias_plazo;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _modificado_por;
		
		private System.Nullable<System.DateTime> _modificado_el;
		
		private string _vendedor;
		
		private System.Nullable<int> _acepta_impuesto;
		
		private string _observaciones;
		
		private System.Nullable<int> _mostrar_obs_fact;
		
		private System.Nullable<decimal> _compania;
		
		private System.Nullable<decimal> _animo;
		
		private string _correo_actualizado_por;
		
		private System.Nullable<System.DateTime> _correo_actualizado_el;
		
		private string _correo_anterior;
		
		private System.Nullable<int> _CedulaCorrecta;
		
		private System.Nullable<decimal> _venta_mes_anterior;
		
		private System.Nullable<decimal> _saldo_vendido;
		
		private EntitySet<factura> _facturas;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void Oncliente1Changing(string value);
    partial void Oncliente1Changed();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onapellido_01Changing(string value);
    partial void Onapellido_01Changed();
    partial void Onapellido_02Changing(string value);
    partial void Onapellido_02Changed();
    partial void OntipoChanging(decimal value);
    partial void OntipoChanged();
    partial void OnzonaChanging(string value);
    partial void OnzonaChanged();
    partial void Ontipo_de_identificacionChanging(string value);
    partial void Ontipo_de_identificacionChanged();
    partial void OnestadoChanging(decimal value);
    partial void OnestadoChanged();
    partial void OnprovinciaChanging(string value);
    partial void OnprovinciaChanged();
    partial void OncantonChanging(string value);
    partial void OncantonChanged();
    partial void OndistritoChanging(string value);
    partial void OndistritoChanged();
    partial void OnBarrioChanging(string value);
    partial void OnBarrioChanged();
    partial void OnidentificacionChanging(string value);
    partial void OnidentificacionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Ontelefono_01Changing(string value);
    partial void Ontelefono_01Changed();
    partial void Ontelefono_02Changing(string value);
    partial void Ontelefono_02Changed();
    partial void Ontelefono_03Changing(string value);
    partial void Ontelefono_03Changed();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnrepresentanteChanging(string value);
    partial void OnrepresentanteChanged();
    partial void Onlimite_de_creditoChanging(System.Nullable<decimal> value);
    partial void Onlimite_de_creditoChanged();
    partial void Ondescuento_generalChanging(System.Nullable<decimal> value);
    partial void Ondescuento_generalChanged();
    partial void Ondias_plazoChanging(System.Nullable<decimal> value);
    partial void Ondias_plazoChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Onmodificado_porChanging(string value);
    partial void Onmodificado_porChanged();
    partial void Onmodificado_elChanging(System.Nullable<System.DateTime> value);
    partial void Onmodificado_elChanged();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void Onacepta_impuestoChanging(System.Nullable<int> value);
    partial void Onacepta_impuestoChanged();
    partial void OnobservacionesChanging(string value);
    partial void OnobservacionesChanged();
    partial void Onmostrar_obs_factChanging(System.Nullable<int> value);
    partial void Onmostrar_obs_factChanged();
    partial void OncompaniaChanging(System.Nullable<decimal> value);
    partial void OncompaniaChanged();
    partial void OnanimoChanging(System.Nullable<decimal> value);
    partial void OnanimoChanged();
    partial void Oncorreo_actualizado_porChanging(string value);
    partial void Oncorreo_actualizado_porChanged();
    partial void Oncorreo_actualizado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncorreo_actualizado_elChanged();
    partial void Oncorreo_anteriorChanging(string value);
    partial void Oncorreo_anteriorChanged();
    partial void OnCedulaCorrectaChanging(System.Nullable<int> value);
    partial void OnCedulaCorrectaChanged();
    partial void Onventa_mes_anteriorChanging(System.Nullable<decimal> value);
    partial void Onventa_mes_anteriorChanged();
    partial void Onsaldo_vendidoChanging(System.Nullable<decimal> value);
    partial void Onsaldo_vendidoChanged();
    #endregion
		
		public cliente()
		{
			this._facturas = new EntitySet<factura>(new Action<factura>(this.attach_facturas), new Action<factura>(this.detach_facturas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cliente", Storage="_cliente1", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cliente1
		{
			get
			{
				return this._cliente1;
			}
			set
			{
				if ((this._cliente1 != value))
				{
					this.Oncliente1Changing(value);
					this.SendPropertyChanging();
					this._cliente1 = value;
					this.SendPropertyChanged("cliente1");
					this.Oncliente1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_01", DbType="VarChar(255)")]
		public string apellido_01
		{
			get
			{
				return this._apellido_01;
			}
			set
			{
				if ((this._apellido_01 != value))
				{
					this.Onapellido_01Changing(value);
					this.SendPropertyChanging();
					this._apellido_01 = value;
					this.SendPropertyChanged("apellido_01");
					this.Onapellido_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_02", DbType="VarChar(255)")]
		public string apellido_02
		{
			get
			{
				return this._apellido_02;
			}
			set
			{
				if ((this._apellido_02 != value))
				{
					this.Onapellido_02Changing(value);
					this.SendPropertyChanging();
					this._apellido_02 = value;
					this.SendPropertyChanged("apellido_02");
					this.Onapellido_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Decimal(18,0) NOT NULL")]
		public decimal tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				if ((this._zona != value))
				{
					this.OnzonaChanging(value);
					this.SendPropertyChanging();
					this._zona = value;
					this.SendPropertyChanged("zona");
					this.OnzonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_de_identificacion", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string tipo_de_identificacion
		{
			get
			{
				return this._tipo_de_identificacion;
			}
			set
			{
				if ((this._tipo_de_identificacion != value))
				{
					this.Ontipo_de_identificacionChanging(value);
					this.SendPropertyChanging();
					this._tipo_de_identificacion = value;
					this.SendPropertyChanged("tipo_de_identificacion");
					this.Ontipo_de_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Decimal(4,0) NOT NULL")]
		public decimal estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="VarChar(1)")]
		public string provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this.OnprovinciaChanging(value);
					this.SendPropertyChanging();
					this._provincia = value;
					this.SendPropertyChanged("provincia");
					this.OnprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="VarChar(2)")]
		public string canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this.OncantonChanging(value);
					this.SendPropertyChanging();
					this._canton = value;
					this.SendPropertyChanged("canton");
					this.OncantonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="VarChar(2)")]
		public string distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this.OndistritoChanging(value);
					this.SendPropertyChanging();
					this._distrito = value;
					this.SendPropertyChanged("distrito");
					this.OndistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barrio", DbType="VarChar(2)")]
		public string Barrio
		{
			get
			{
				return this._Barrio;
			}
			set
			{
				if ((this._Barrio != value))
				{
					this.OnBarrioChanging(value);
					this.SendPropertyChanging();
					this._Barrio = value;
					this.SendPropertyChanged("Barrio");
					this.OnBarrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificacion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string identificacion
		{
			get
			{
				return this._identificacion;
			}
			set
			{
				if ((this._identificacion != value))
				{
					this.OnidentificacionChanging(value);
					this.SendPropertyChanging();
					this._identificacion = value;
					this.SendPropertyChanged("identificacion");
					this.OnidentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_01", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono_01
		{
			get
			{
				return this._telefono_01;
			}
			set
			{
				if ((this._telefono_01 != value))
				{
					this.Ontelefono_01Changing(value);
					this.SendPropertyChanging();
					this._telefono_01 = value;
					this.SendPropertyChanged("telefono_01");
					this.Ontelefono_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_02", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono_02
		{
			get
			{
				return this._telefono_02;
			}
			set
			{
				if ((this._telefono_02 != value))
				{
					this.Ontelefono_02Changing(value);
					this.SendPropertyChanging();
					this._telefono_02 = value;
					this.SendPropertyChanged("telefono_02");
					this.Ontelefono_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_03", DbType="VarChar(50)")]
		public string telefono_03
		{
			get
			{
				return this._telefono_03;
			}
			set
			{
				if ((this._telefono_03 != value))
				{
					this.Ontelefono_03Changing(value);
					this.SendPropertyChanging();
					this._telefono_03 = value;
					this.SendPropertyChanged("telefono_03");
					this.Ontelefono_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_representante", DbType="VarChar(100)")]
		public string representante
		{
			get
			{
				return this._representante;
			}
			set
			{
				if ((this._representante != value))
				{
					this.OnrepresentanteChanging(value);
					this.SendPropertyChanging();
					this._representante = value;
					this.SendPropertyChanged("representante");
					this.OnrepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limite_de_credito", DbType="Money")]
		public System.Nullable<decimal> limite_de_credito
		{
			get
			{
				return this._limite_de_credito;
			}
			set
			{
				if ((this._limite_de_credito != value))
				{
					this.Onlimite_de_creditoChanging(value);
					this.SendPropertyChanging();
					this._limite_de_credito = value;
					this.SendPropertyChanged("limite_de_credito");
					this.Onlimite_de_creditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento_general", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> descuento_general
		{
			get
			{
				return this._descuento_general;
			}
			set
			{
				if ((this._descuento_general != value))
				{
					this.Ondescuento_generalChanging(value);
					this.SendPropertyChanging();
					this._descuento_general = value;
					this.SendPropertyChanged("descuento_general");
					this.Ondescuento_generalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias_plazo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dias_plazo
		{
			get
			{
				return this._dias_plazo;
			}
			set
			{
				if ((this._dias_plazo != value))
				{
					this.Ondias_plazoChanging(value);
					this.SendPropertyChanging();
					this._dias_plazo = value;
					this.SendPropertyChanged("dias_plazo");
					this.Ondias_plazoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(255)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_por", DbType="VarChar(255)")]
		public string modificado_por
		{
			get
			{
				return this._modificado_por;
			}
			set
			{
				if ((this._modificado_por != value))
				{
					this.Onmodificado_porChanging(value);
					this.SendPropertyChanging();
					this._modificado_por = value;
					this.SendPropertyChanged("modificado_por");
					this.Onmodificado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificado_el
		{
			get
			{
				return this._modificado_el;
			}
			set
			{
				if ((this._modificado_el != value))
				{
					this.Onmodificado_elChanging(value);
					this.SendPropertyChanging();
					this._modificado_el = value;
					this.SendPropertyChanged("modificado_el");
					this.Onmodificado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(30)")]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acepta_impuesto", DbType="Int")]
		public System.Nullable<int> acepta_impuesto
		{
			get
			{
				return this._acepta_impuesto;
			}
			set
			{
				if ((this._acepta_impuesto != value))
				{
					this.Onacepta_impuestoChanging(value);
					this.SendPropertyChanging();
					this._acepta_impuesto = value;
					this.SendPropertyChanged("acepta_impuesto");
					this.Onacepta_impuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(500)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this.OnobservacionesChanging(value);
					this.SendPropertyChanging();
					this._observaciones = value;
					this.SendPropertyChanged("observaciones");
					this.OnobservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostrar_obs_fact", DbType="Int")]
		public System.Nullable<int> mostrar_obs_fact
		{
			get
			{
				return this._mostrar_obs_fact;
			}
			set
			{
				if ((this._mostrar_obs_fact != value))
				{
					this.Onmostrar_obs_factChanging(value);
					this.SendPropertyChanging();
					this._mostrar_obs_fact = value;
					this.SendPropertyChanged("mostrar_obs_fact");
					this.Onmostrar_obs_factChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compania", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> compania
		{
			get
			{
				return this._compania;
			}
			set
			{
				if ((this._compania != value))
				{
					this.OncompaniaChanging(value);
					this.SendPropertyChanging();
					this._compania = value;
					this.SendPropertyChanged("compania");
					this.OncompaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_animo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> animo
		{
			get
			{
				return this._animo;
			}
			set
			{
				if ((this._animo != value))
				{
					this.OnanimoChanging(value);
					this.SendPropertyChanging();
					this._animo = value;
					this.SendPropertyChanged("animo");
					this.OnanimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_actualizado_por", DbType="VarChar(50)")]
		public string correo_actualizado_por
		{
			get
			{
				return this._correo_actualizado_por;
			}
			set
			{
				if ((this._correo_actualizado_por != value))
				{
					this.Oncorreo_actualizado_porChanging(value);
					this.SendPropertyChanging();
					this._correo_actualizado_por = value;
					this.SendPropertyChanged("correo_actualizado_por");
					this.Oncorreo_actualizado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_actualizado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> correo_actualizado_el
		{
			get
			{
				return this._correo_actualizado_el;
			}
			set
			{
				if ((this._correo_actualizado_el != value))
				{
					this.Oncorreo_actualizado_elChanging(value);
					this.SendPropertyChanging();
					this._correo_actualizado_el = value;
					this.SendPropertyChanged("correo_actualizado_el");
					this.Oncorreo_actualizado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_anterior", DbType="VarChar(200)")]
		public string correo_anterior
		{
			get
			{
				return this._correo_anterior;
			}
			set
			{
				if ((this._correo_anterior != value))
				{
					this.Oncorreo_anteriorChanging(value);
					this.SendPropertyChanging();
					this._correo_anterior = value;
					this.SendPropertyChanged("correo_anterior");
					this.Oncorreo_anteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedulaCorrecta", DbType="Int")]
		public System.Nullable<int> CedulaCorrecta
		{
			get
			{
				return this._CedulaCorrecta;
			}
			set
			{
				if ((this._CedulaCorrecta != value))
				{
					this.OnCedulaCorrectaChanging(value);
					this.SendPropertyChanging();
					this._CedulaCorrecta = value;
					this.SendPropertyChanged("CedulaCorrecta");
					this.OnCedulaCorrectaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venta_mes_anterior", DbType="Money")]
		public System.Nullable<decimal> venta_mes_anterior
		{
			get
			{
				return this._venta_mes_anterior;
			}
			set
			{
				if ((this._venta_mes_anterior != value))
				{
					this.Onventa_mes_anteriorChanging(value);
					this.SendPropertyChanging();
					this._venta_mes_anterior = value;
					this.SendPropertyChanged("venta_mes_anterior");
					this.Onventa_mes_anteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_vendido", DbType="Money")]
		public System.Nullable<decimal> saldo_vendido
		{
			get
			{
				return this._saldo_vendido;
			}
			set
			{
				if ((this._saldo_vendido != value))
				{
					this.Onsaldo_vendidoChanging(value);
					this.SendPropertyChanging();
					this._saldo_vendido = value;
					this.SendPropertyChanged("saldo_vendido");
					this.Onsaldo_vendidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_factura", Storage="_facturas", ThisKey="cliente1", OtherKey="cliente")]
		public EntitySet<factura> facturas
		{
			get
			{
				return this._facturas;
			}
			set
			{
				this._facturas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_facturas(factura entity)
		{
			this.SendPropertyChanging();
			entity.cliente1 = this;
		}
		
		private void detach_facturas(factura entity)
		{
			this.SendPropertyChanging();
			entity.cliente1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.facturas_encabezado")]
	public partial class factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<decimal> _compania;
		
		private string _num_orden;
		
		private decimal _tipo;
		
		private string _cliente;
		
		private string _cobrador;
		
		private string _vendedor;
		
		private string _bodega;
		
		private System.Nullable<decimal> _tipo_orden;
		
		private string _referencia_cliente;
		
		private System.Nullable<decimal> _Cierre;
		
		private System.Nullable<decimal> _CierreMensual;
		
		private System.Nullable<decimal> _meses_plazo;
		
		private System.Nullable<decimal> _CierreDiario;
		
		private string _referencia;
		
		private string _zona;
		
		private System.Nullable<decimal> _estado;
		
		private System.Nullable<decimal> _transporte;
		
		private System.DateTime _fecha;
		
		private System.Nullable<System.DateTime> _fecha_vencimiento;
		
		private System.DateTime _FechadePago;
		
		private System.Nullable<System.DateTime> _fecha_ultimo_pago;
		
		private System.Nullable<decimal> _subtotal_con_impuesto;
		
		private System.Nullable<decimal> _subtotal_sin_impuesto;
		
		private System.Nullable<decimal> _total_impuesto_ventas;
		
		private System.Nullable<decimal> _total_impuesto_consumo;
		
		private System.Nullable<decimal> _total_monto_comision;
		
		private System.Nullable<decimal> _monto_descuento_factura;
		
		private System.Nullable<decimal> _monto_descuento_global;
		
		private System.Nullable<decimal> _monto_descuento_monto;
		
		private System.Nullable<decimal> _monto_intereses_por_mora;
		
		private System.Nullable<decimal> _saldo_intereses_por_mora;
		
		private System.Nullable<decimal> _linea1;
		
		private System.Nullable<decimal> _monto_bruto;
		
		private System.Nullable<decimal> _monto_total;
		
		private System.Nullable<decimal> _saldo_factura;
		
		private System.Nullable<decimal> _tipo_de_pago;
		
		private decimal _porcentaje_impuesto_ventas;
		
		private System.Nullable<decimal> _porcentaje_descuento_factura;
		
		private System.Nullable<decimal> _porcentaje_descuento_global;
		
		private System.Nullable<decimal> _porcentaje_comision;
		
		private System.Nullable<decimal> _porcentaje_comision2;
		
		private System.Nullable<decimal> _porcentaje_intereses;
		
		private System.Nullable<decimal> _porcentaje_comision_lider;
		
		private System.Nullable<decimal> _monto_cupon;
		
		private System.Nullable<decimal> _handing;
		
		private System.Nullable<decimal> _monto_transporte;
		
		private string _anulacion_salida_por;
		
		private System.Nullable<decimal> _mercancia_salida;
		
		private System.Nullable<System.DateTime> _fecha_salida_mercancia;
		
		private string _despachado_por;
		
		private System.Nullable<decimal> _recargo;
		
		private string _observacion;
		
		private System.Nullable<decimal> _estado_entrega;
		
		private System.Nullable<decimal> _forma_despacho;
		
		private string _enviar_a;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _modificado_por;
		
		private System.Nullable<System.DateTime> _modificado_el;
		
		private System.Nullable<decimal> _estado_cobro;
		
		private string _cupon;
		
		private System.Nullable<decimal> _prioridad;
		
		private string _descripcion_factura;
		
		private System.Nullable<decimal> _monto_bruto_real;
		
		private System.Nullable<decimal> _cierre_inventario;
		
		private System.Nullable<decimal> _dias_atrasada;
		
		private System.Nullable<decimal> _PrimeraCuota;
		
		private System.Nullable<decimal> _CuotaMensual;
		
		private System.Nullable<decimal> _OrdenOriginal;
		
		private System.Nullable<decimal> _SolicitaEstudio;
		
		private System.Nullable<decimal> _MontoEntregaInmediata;
		
		private System.Nullable<decimal> _postventa;
		
		private System.Nullable<decimal> _plan_mercadeo;
		
		private System.Nullable<decimal> _Verificada;
		
		private decimal _consecutivo;
		
		private System.Nullable<decimal> _CierreCreacion;
		
		private System.Nullable<decimal> _MontoLocalizacion;
		
		private System.Nullable<int> _deduccion_tarjeta;
		
		private System.Nullable<int> _actualizada;
		
		private System.Nullable<int> _insertada;
		
		private string _ref;
		
		private System.Nullable<int> _EntregaInmediata;
		
		private System.Nullable<int> _Reclasificacion;
		
		private System.Nullable<int> _CuotasReclasificacion;
		
		private EntityRef<cliente> _cliente1;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncompaniaChanging(System.Nullable<decimal> value);
    partial void OncompaniaChanged();
    partial void Onnum_ordenChanging(string value);
    partial void Onnum_ordenChanged();
    partial void OntipoChanging(decimal value);
    partial void OntipoChanged();
    partial void OnclienteChanging(string value);
    partial void OnclienteChanged();
    partial void OncobradorChanging(string value);
    partial void OncobradorChanged();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void OnbodegaChanging(string value);
    partial void OnbodegaChanged();
    partial void Ontipo_ordenChanging(System.Nullable<decimal> value);
    partial void Ontipo_ordenChanged();
    partial void Onreferencia_clienteChanging(string value);
    partial void Onreferencia_clienteChanged();
    partial void OnCierreChanging(System.Nullable<decimal> value);
    partial void OnCierreChanged();
    partial void OnCierreMensualChanging(System.Nullable<decimal> value);
    partial void OnCierreMensualChanged();
    partial void Onmeses_plazoChanging(System.Nullable<decimal> value);
    partial void Onmeses_plazoChanged();
    partial void OnCierreDiarioChanging(System.Nullable<decimal> value);
    partial void OnCierreDiarioChanged();
    partial void OnreferenciaChanging(string value);
    partial void OnreferenciaChanged();
    partial void OnzonaChanging(string value);
    partial void OnzonaChanged();
    partial void OnestadoChanging(System.Nullable<decimal> value);
    partial void OnestadoChanged();
    partial void OntransporteChanging(System.Nullable<decimal> value);
    partial void OntransporteChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void Onfecha_vencimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_vencimientoChanged();
    partial void OnFechadePagoChanging(System.DateTime value);
    partial void OnFechadePagoChanged();
    partial void Onfecha_ultimo_pagoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ultimo_pagoChanged();
    partial void Onsubtotal_con_impuestoChanging(System.Nullable<decimal> value);
    partial void Onsubtotal_con_impuestoChanged();
    partial void Onsubtotal_sin_impuestoChanging(System.Nullable<decimal> value);
    partial void Onsubtotal_sin_impuestoChanged();
    partial void Ontotal_impuesto_ventasChanging(System.Nullable<decimal> value);
    partial void Ontotal_impuesto_ventasChanged();
    partial void Ontotal_impuesto_consumoChanging(System.Nullable<decimal> value);
    partial void Ontotal_impuesto_consumoChanged();
    partial void Ontotal_monto_comisionChanging(System.Nullable<decimal> value);
    partial void Ontotal_monto_comisionChanged();
    partial void Onmonto_descuento_facturaChanging(System.Nullable<decimal> value);
    partial void Onmonto_descuento_facturaChanged();
    partial void Onmonto_descuento_globalChanging(System.Nullable<decimal> value);
    partial void Onmonto_descuento_globalChanged();
    partial void Onmonto_descuento_montoChanging(System.Nullable<decimal> value);
    partial void Onmonto_descuento_montoChanged();
    partial void Onmonto_intereses_por_moraChanging(System.Nullable<decimal> value);
    partial void Onmonto_intereses_por_moraChanged();
    partial void Onsaldo_intereses_por_moraChanging(System.Nullable<decimal> value);
    partial void Onsaldo_intereses_por_moraChanged();
    partial void Onlinea1Changing(System.Nullable<decimal> value);
    partial void Onlinea1Changed();
    partial void Onmonto_brutoChanging(System.Nullable<decimal> value);
    partial void Onmonto_brutoChanged();
    partial void Onmonto_totalChanging(System.Nullable<decimal> value);
    partial void Onmonto_totalChanged();
    partial void Onsaldo_facturaChanging(System.Nullable<decimal> value);
    partial void Onsaldo_facturaChanged();
    partial void Ontipo_de_pagoChanging(System.Nullable<decimal> value);
    partial void Ontipo_de_pagoChanged();
    partial void Onporcentaje_impuesto_ventasChanging(decimal value);
    partial void Onporcentaje_impuesto_ventasChanged();
    partial void Onporcentaje_descuento_facturaChanging(System.Nullable<decimal> value);
    partial void Onporcentaje_descuento_facturaChanged();
    partial void Onporcentaje_descuento_globalChanging(System.Nullable<decimal> value);
    partial void Onporcentaje_descuento_globalChanged();
    partial void Onporcentaje_comisionChanging(System.Nullable<decimal> value);
    partial void Onporcentaje_comisionChanged();
    partial void Onporcentaje_comision2Changing(System.Nullable<decimal> value);
    partial void Onporcentaje_comision2Changed();
    partial void Onporcentaje_interesesChanging(System.Nullable<decimal> value);
    partial void Onporcentaje_interesesChanged();
    partial void Onporcentaje_comision_liderChanging(System.Nullable<decimal> value);
    partial void Onporcentaje_comision_liderChanged();
    partial void Onmonto_cuponChanging(System.Nullable<decimal> value);
    partial void Onmonto_cuponChanged();
    partial void OnhandingChanging(System.Nullable<decimal> value);
    partial void OnhandingChanged();
    partial void Onmonto_transporteChanging(System.Nullable<decimal> value);
    partial void Onmonto_transporteChanged();
    partial void Onanulacion_salida_porChanging(string value);
    partial void Onanulacion_salida_porChanged();
    partial void Onmercancia_salidaChanging(System.Nullable<decimal> value);
    partial void Onmercancia_salidaChanged();
    partial void Onfecha_salida_mercanciaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_salida_mercanciaChanged();
    partial void Ondespachado_porChanging(string value);
    partial void Ondespachado_porChanged();
    partial void OnrecargoChanging(System.Nullable<decimal> value);
    partial void OnrecargoChanged();
    partial void OnobservacionChanging(string value);
    partial void OnobservacionChanged();
    partial void Onestado_entregaChanging(System.Nullable<decimal> value);
    partial void Onestado_entregaChanged();
    partial void Onforma_despachoChanging(System.Nullable<decimal> value);
    partial void Onforma_despachoChanged();
    partial void Onenviar_aChanging(string value);
    partial void Onenviar_aChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Onmodificado_porChanging(string value);
    partial void Onmodificado_porChanged();
    partial void Onmodificado_elChanging(System.Nullable<System.DateTime> value);
    partial void Onmodificado_elChanged();
    partial void Onestado_cobroChanging(System.Nullable<decimal> value);
    partial void Onestado_cobroChanged();
    partial void OncuponChanging(string value);
    partial void OncuponChanged();
    partial void OnprioridadChanging(System.Nullable<decimal> value);
    partial void OnprioridadChanged();
    partial void Ondescripcion_facturaChanging(string value);
    partial void Ondescripcion_facturaChanged();
    partial void Onmonto_bruto_realChanging(System.Nullable<decimal> value);
    partial void Onmonto_bruto_realChanged();
    partial void Oncierre_inventarioChanging(System.Nullable<decimal> value);
    partial void Oncierre_inventarioChanged();
    partial void Ondias_atrasadaChanging(System.Nullable<decimal> value);
    partial void Ondias_atrasadaChanged();
    partial void OnPrimeraCuotaChanging(System.Nullable<decimal> value);
    partial void OnPrimeraCuotaChanged();
    partial void OnCuotaMensualChanging(System.Nullable<decimal> value);
    partial void OnCuotaMensualChanged();
    partial void OnOrdenOriginalChanging(System.Nullable<decimal> value);
    partial void OnOrdenOriginalChanged();
    partial void OnSolicitaEstudioChanging(System.Nullable<decimal> value);
    partial void OnSolicitaEstudioChanged();
    partial void OnMontoEntregaInmediataChanging(System.Nullable<decimal> value);
    partial void OnMontoEntregaInmediataChanged();
    partial void OnpostventaChanging(System.Nullable<decimal> value);
    partial void OnpostventaChanged();
    partial void Onplan_mercadeoChanging(System.Nullable<decimal> value);
    partial void Onplan_mercadeoChanged();
    partial void OnVerificadaChanging(System.Nullable<decimal> value);
    partial void OnVerificadaChanged();
    partial void OnconsecutivoChanging(decimal value);
    partial void OnconsecutivoChanged();
    partial void OnCierreCreacionChanging(System.Nullable<decimal> value);
    partial void OnCierreCreacionChanged();
    partial void OnMontoLocalizacionChanging(System.Nullable<decimal> value);
    partial void OnMontoLocalizacionChanged();
    partial void Ondeduccion_tarjetaChanging(System.Nullable<int> value);
    partial void Ondeduccion_tarjetaChanged();
    partial void OnactualizadaChanging(System.Nullable<int> value);
    partial void OnactualizadaChanged();
    partial void OninsertadaChanging(System.Nullable<int> value);
    partial void OninsertadaChanged();
    partial void OnrefChanging(string value);
    partial void OnrefChanged();
    partial void OnEntregaInmediataChanging(System.Nullable<int> value);
    partial void OnEntregaInmediataChanged();
    partial void OnReclasificacionChanging(System.Nullable<int> value);
    partial void OnReclasificacionChanged();
    partial void OnCuotasReclasificacionChanging(System.Nullable<int> value);
    partial void OnCuotasReclasificacionChanged();
    #endregion
		
		public factura()
		{
			this._cliente1 = default(EntityRef<cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compania", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> compania
		{
			get
			{
				return this._compania;
			}
			set
			{
				if ((this._compania != value))
				{
					this.OncompaniaChanging(value);
					this.SendPropertyChanging();
					this._compania = value;
					this.SendPropertyChanged("compania");
					this.OncompaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="factura", Storage="_num_orden", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string num_orden
		{
			get
			{
				return this._num_orden;
			}
			set
			{
				if ((this._num_orden != value))
				{
					this.Onnum_ordenChanging(value);
					this.SendPropertyChanging();
					this._num_orden = value;
					this.SendPropertyChanged("num_orden");
					this.Onnum_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Decimal(18,0) NOT NULL")]
		public decimal tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cliente", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cliente
		{
			get
			{
				return this._cliente;
			}
			set
			{
				if ((this._cliente != value))
				{
					if (this._cliente1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclienteChanging(value);
					this.SendPropertyChanging();
					this._cliente = value;
					this.SendPropertyChanged("cliente");
					this.OnclienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cobrador", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string cobrador
		{
			get
			{
				return this._cobrador;
			}
			set
			{
				if ((this._cobrador != value))
				{
					this.OncobradorChanging(value);
					this.SendPropertyChanging();
					this._cobrador = value;
					this.SendPropertyChanged("cobrador");
					this.OncobradorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bodega", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string bodega
		{
			get
			{
				return this._bodega;
			}
			set
			{
				if ((this._bodega != value))
				{
					this.OnbodegaChanging(value);
					this.SendPropertyChanging();
					this._bodega = value;
					this.SendPropertyChanged("bodega");
					this.OnbodegaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_orden", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> tipo_orden
		{
			get
			{
				return this._tipo_orden;
			}
			set
			{
				if ((this._tipo_orden != value))
				{
					this.Ontipo_ordenChanging(value);
					this.SendPropertyChanging();
					this._tipo_orden = value;
					this.SendPropertyChanged("tipo_orden");
					this.Ontipo_ordenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_cliente", DbType="VarChar(30)")]
		public string referencia_cliente
		{
			get
			{
				return this._referencia_cliente;
			}
			set
			{
				if ((this._referencia_cliente != value))
				{
					this.Onreferencia_clienteChanging(value);
					this.SendPropertyChanging();
					this._referencia_cliente = value;
					this.SendPropertyChanged("referencia_cliente");
					this.Onreferencia_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cierre", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Cierre
		{
			get
			{
				return this._Cierre;
			}
			set
			{
				if ((this._Cierre != value))
				{
					this.OnCierreChanging(value);
					this.SendPropertyChanging();
					this._Cierre = value;
					this.SendPropertyChanged("Cierre");
					this.OnCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CierreMensual", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CierreMensual
		{
			get
			{
				return this._CierreMensual;
			}
			set
			{
				if ((this._CierreMensual != value))
				{
					this.OnCierreMensualChanging(value);
					this.SendPropertyChanging();
					this._CierreMensual = value;
					this.SendPropertyChanged("CierreMensual");
					this.OnCierreMensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meses_plazo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> meses_plazo
		{
			get
			{
				return this._meses_plazo;
			}
			set
			{
				if ((this._meses_plazo != value))
				{
					this.Onmeses_plazoChanging(value);
					this.SendPropertyChanging();
					this._meses_plazo = value;
					this.SendPropertyChanged("meses_plazo");
					this.Onmeses_plazoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CierreDiario", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CierreDiario
		{
			get
			{
				return this._CierreDiario;
			}
			set
			{
				if ((this._CierreDiario != value))
				{
					this.OnCierreDiarioChanging(value);
					this.SendPropertyChanging();
					this._CierreDiario = value;
					this.SendPropertyChanged("CierreDiario");
					this.OnCierreDiarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia", DbType="VarChar(16)")]
		public string referencia
		{
			get
			{
				return this._referencia;
			}
			set
			{
				if ((this._referencia != value))
				{
					this.OnreferenciaChanging(value);
					this.SendPropertyChanging();
					this._referencia = value;
					this.SendPropertyChanged("referencia");
					this.OnreferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona", DbType="VarChar(16)")]
		public string zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				if ((this._zona != value))
				{
					this.OnzonaChanging(value);
					this.SendPropertyChanging();
					this._zona = value;
					this.SendPropertyChanged("zona");
					this.OnzonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_transporte", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> transporte
		{
			get
			{
				return this._transporte;
			}
			set
			{
				if ((this._transporte != value))
				{
					this.OntransporteChanging(value);
					this.SendPropertyChanging();
					this._transporte = value;
					this.SendPropertyChanged("transporte");
					this.OntransporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_vencimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_vencimiento
		{
			get
			{
				return this._fecha_vencimiento;
			}
			set
			{
				if ((this._fecha_vencimiento != value))
				{
					this.Onfecha_vencimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_vencimiento = value;
					this.SendPropertyChanged("fecha_vencimiento");
					this.Onfecha_vencimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechadePago", DbType="DateTime NOT NULL")]
		public System.DateTime FechadePago
		{
			get
			{
				return this._FechadePago;
			}
			set
			{
				if ((this._FechadePago != value))
				{
					this.OnFechadePagoChanging(value);
					this.SendPropertyChanging();
					this._FechadePago = value;
					this.SendPropertyChanged("FechadePago");
					this.OnFechadePagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ultimo_pago", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_ultimo_pago
		{
			get
			{
				return this._fecha_ultimo_pago;
			}
			set
			{
				if ((this._fecha_ultimo_pago != value))
				{
					this.Onfecha_ultimo_pagoChanging(value);
					this.SendPropertyChanging();
					this._fecha_ultimo_pago = value;
					this.SendPropertyChanged("fecha_ultimo_pago");
					this.Onfecha_ultimo_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal_con_impuesto", DbType="Money")]
		public System.Nullable<decimal> subtotal_con_impuesto
		{
			get
			{
				return this._subtotal_con_impuesto;
			}
			set
			{
				if ((this._subtotal_con_impuesto != value))
				{
					this.Onsubtotal_con_impuestoChanging(value);
					this.SendPropertyChanging();
					this._subtotal_con_impuesto = value;
					this.SendPropertyChanged("subtotal_con_impuesto");
					this.Onsubtotal_con_impuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtotal_sin_impuesto", DbType="Money")]
		public System.Nullable<decimal> subtotal_sin_impuesto
		{
			get
			{
				return this._subtotal_sin_impuesto;
			}
			set
			{
				if ((this._subtotal_sin_impuesto != value))
				{
					this.Onsubtotal_sin_impuestoChanging(value);
					this.SendPropertyChanging();
					this._subtotal_sin_impuesto = value;
					this.SendPropertyChanged("subtotal_sin_impuesto");
					this.Onsubtotal_sin_impuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_impuesto_ventas", DbType="Money")]
		public System.Nullable<decimal> total_impuesto_ventas
		{
			get
			{
				return this._total_impuesto_ventas;
			}
			set
			{
				if ((this._total_impuesto_ventas != value))
				{
					this.Ontotal_impuesto_ventasChanging(value);
					this.SendPropertyChanging();
					this._total_impuesto_ventas = value;
					this.SendPropertyChanged("total_impuesto_ventas");
					this.Ontotal_impuesto_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_impuesto_consumo", DbType="Money")]
		public System.Nullable<decimal> total_impuesto_consumo
		{
			get
			{
				return this._total_impuesto_consumo;
			}
			set
			{
				if ((this._total_impuesto_consumo != value))
				{
					this.Ontotal_impuesto_consumoChanging(value);
					this.SendPropertyChanging();
					this._total_impuesto_consumo = value;
					this.SendPropertyChanged("total_impuesto_consumo");
					this.Ontotal_impuesto_consumoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_monto_comision", DbType="Money")]
		public System.Nullable<decimal> total_monto_comision
		{
			get
			{
				return this._total_monto_comision;
			}
			set
			{
				if ((this._total_monto_comision != value))
				{
					this.Ontotal_monto_comisionChanging(value);
					this.SendPropertyChanging();
					this._total_monto_comision = value;
					this.SendPropertyChanged("total_monto_comision");
					this.Ontotal_monto_comisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_descuento_factura", DbType="Money")]
		public System.Nullable<decimal> monto_descuento_factura
		{
			get
			{
				return this._monto_descuento_factura;
			}
			set
			{
				if ((this._monto_descuento_factura != value))
				{
					this.Onmonto_descuento_facturaChanging(value);
					this.SendPropertyChanging();
					this._monto_descuento_factura = value;
					this.SendPropertyChanged("monto_descuento_factura");
					this.Onmonto_descuento_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_descuento_global", DbType="Money")]
		public System.Nullable<decimal> monto_descuento_global
		{
			get
			{
				return this._monto_descuento_global;
			}
			set
			{
				if ((this._monto_descuento_global != value))
				{
					this.Onmonto_descuento_globalChanging(value);
					this.SendPropertyChanging();
					this._monto_descuento_global = value;
					this.SendPropertyChanged("monto_descuento_global");
					this.Onmonto_descuento_globalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_descuento_monto", DbType="Money")]
		public System.Nullable<decimal> monto_descuento_monto
		{
			get
			{
				return this._monto_descuento_monto;
			}
			set
			{
				if ((this._monto_descuento_monto != value))
				{
					this.Onmonto_descuento_montoChanging(value);
					this.SendPropertyChanging();
					this._monto_descuento_monto = value;
					this.SendPropertyChanged("monto_descuento_monto");
					this.Onmonto_descuento_montoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_intereses_por_mora", DbType="Money")]
		public System.Nullable<decimal> monto_intereses_por_mora
		{
			get
			{
				return this._monto_intereses_por_mora;
			}
			set
			{
				if ((this._monto_intereses_por_mora != value))
				{
					this.Onmonto_intereses_por_moraChanging(value);
					this.SendPropertyChanging();
					this._monto_intereses_por_mora = value;
					this.SendPropertyChanged("monto_intereses_por_mora");
					this.Onmonto_intereses_por_moraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_intereses_por_mora", DbType="Money")]
		public System.Nullable<decimal> saldo_intereses_por_mora
		{
			get
			{
				return this._saldo_intereses_por_mora;
			}
			set
			{
				if ((this._saldo_intereses_por_mora != value))
				{
					this.Onsaldo_intereses_por_moraChanging(value);
					this.SendPropertyChanging();
					this._saldo_intereses_por_mora = value;
					this.SendPropertyChanged("saldo_intereses_por_mora");
					this.Onsaldo_intereses_por_moraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linea1", DbType="Money")]
		public System.Nullable<decimal> linea1
		{
			get
			{
				return this._linea1;
			}
			set
			{
				if ((this._linea1 != value))
				{
					this.Onlinea1Changing(value);
					this.SendPropertyChanging();
					this._linea1 = value;
					this.SendPropertyChanged("linea1");
					this.Onlinea1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_bruto", DbType="Money")]
		public System.Nullable<decimal> monto_bruto
		{
			get
			{
				return this._monto_bruto;
			}
			set
			{
				if ((this._monto_bruto != value))
				{
					this.Onmonto_brutoChanging(value);
					this.SendPropertyChanging();
					this._monto_bruto = value;
					this.SendPropertyChanged("monto_bruto");
					this.Onmonto_brutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_total", DbType="Money")]
		public System.Nullable<decimal> monto_total
		{
			get
			{
				return this._monto_total;
			}
			set
			{
				if ((this._monto_total != value))
				{
					this.Onmonto_totalChanging(value);
					this.SendPropertyChanging();
					this._monto_total = value;
					this.SendPropertyChanged("monto_total");
					this.Onmonto_totalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_factura", DbType="Money")]
		public System.Nullable<decimal> saldo_factura
		{
			get
			{
				return this._saldo_factura;
			}
			set
			{
				if ((this._saldo_factura != value))
				{
					this.Onsaldo_facturaChanging(value);
					this.SendPropertyChanging();
					this._saldo_factura = value;
					this.SendPropertyChanged("saldo_factura");
					this.Onsaldo_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_de_pago", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> tipo_de_pago
		{
			get
			{
				return this._tipo_de_pago;
			}
			set
			{
				if ((this._tipo_de_pago != value))
				{
					this.Ontipo_de_pagoChanging(value);
					this.SendPropertyChanging();
					this._tipo_de_pago = value;
					this.SendPropertyChanged("tipo_de_pago");
					this.Ontipo_de_pagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_impuesto_ventas", DbType="Money NOT NULL")]
		public decimal porcentaje_impuesto_ventas
		{
			get
			{
				return this._porcentaje_impuesto_ventas;
			}
			set
			{
				if ((this._porcentaje_impuesto_ventas != value))
				{
					this.Onporcentaje_impuesto_ventasChanging(value);
					this.SendPropertyChanging();
					this._porcentaje_impuesto_ventas = value;
					this.SendPropertyChanged("porcentaje_impuesto_ventas");
					this.Onporcentaje_impuesto_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_descuento_factura", DbType="Money")]
		public System.Nullable<decimal> porcentaje_descuento_factura
		{
			get
			{
				return this._porcentaje_descuento_factura;
			}
			set
			{
				if ((this._porcentaje_descuento_factura != value))
				{
					this.Onporcentaje_descuento_facturaChanging(value);
					this.SendPropertyChanging();
					this._porcentaje_descuento_factura = value;
					this.SendPropertyChanged("porcentaje_descuento_factura");
					this.Onporcentaje_descuento_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_descuento_global", DbType="Money")]
		public System.Nullable<decimal> porcentaje_descuento_global
		{
			get
			{
				return this._porcentaje_descuento_global;
			}
			set
			{
				if ((this._porcentaje_descuento_global != value))
				{
					this.Onporcentaje_descuento_globalChanging(value);
					this.SendPropertyChanging();
					this._porcentaje_descuento_global = value;
					this.SendPropertyChanged("porcentaje_descuento_global");
					this.Onporcentaje_descuento_globalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_comision", DbType="Money")]
		public System.Nullable<decimal> porcentaje_comision
		{
			get
			{
				return this._porcentaje_comision;
			}
			set
			{
				if ((this._porcentaje_comision != value))
				{
					this.Onporcentaje_comisionChanging(value);
					this.SendPropertyChanging();
					this._porcentaje_comision = value;
					this.SendPropertyChanged("porcentaje_comision");
					this.Onporcentaje_comisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_comision2", DbType="Money")]
		public System.Nullable<decimal> porcentaje_comision2
		{
			get
			{
				return this._porcentaje_comision2;
			}
			set
			{
				if ((this._porcentaje_comision2 != value))
				{
					this.Onporcentaje_comision2Changing(value);
					this.SendPropertyChanging();
					this._porcentaje_comision2 = value;
					this.SendPropertyChanged("porcentaje_comision2");
					this.Onporcentaje_comision2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_intereses", DbType="Money")]
		public System.Nullable<decimal> porcentaje_intereses
		{
			get
			{
				return this._porcentaje_intereses;
			}
			set
			{
				if ((this._porcentaje_intereses != value))
				{
					this.Onporcentaje_interesesChanging(value);
					this.SendPropertyChanging();
					this._porcentaje_intereses = value;
					this.SendPropertyChanged("porcentaje_intereses");
					this.Onporcentaje_interesesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_porcentaje_comision_lider", DbType="Money")]
		public System.Nullable<decimal> porcentaje_comision_lider
		{
			get
			{
				return this._porcentaje_comision_lider;
			}
			set
			{
				if ((this._porcentaje_comision_lider != value))
				{
					this.Onporcentaje_comision_liderChanging(value);
					this.SendPropertyChanging();
					this._porcentaje_comision_lider = value;
					this.SendPropertyChanged("porcentaje_comision_lider");
					this.Onporcentaje_comision_liderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_cupon", DbType="Money")]
		public System.Nullable<decimal> monto_cupon
		{
			get
			{
				return this._monto_cupon;
			}
			set
			{
				if ((this._monto_cupon != value))
				{
					this.Onmonto_cuponChanging(value);
					this.SendPropertyChanging();
					this._monto_cupon = value;
					this.SendPropertyChanged("monto_cupon");
					this.Onmonto_cuponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_handing", DbType="Money")]
		public System.Nullable<decimal> handing
		{
			get
			{
				return this._handing;
			}
			set
			{
				if ((this._handing != value))
				{
					this.OnhandingChanging(value);
					this.SendPropertyChanging();
					this._handing = value;
					this.SendPropertyChanged("handing");
					this.OnhandingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_transporte", DbType="Money")]
		public System.Nullable<decimal> monto_transporte
		{
			get
			{
				return this._monto_transporte;
			}
			set
			{
				if ((this._monto_transporte != value))
				{
					this.Onmonto_transporteChanging(value);
					this.SendPropertyChanging();
					this._monto_transporte = value;
					this.SendPropertyChanged("monto_transporte");
					this.Onmonto_transporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_anulacion_salida_por", DbType="VarChar(50)")]
		public string anulacion_salida_por
		{
			get
			{
				return this._anulacion_salida_por;
			}
			set
			{
				if ((this._anulacion_salida_por != value))
				{
					this.Onanulacion_salida_porChanging(value);
					this.SendPropertyChanging();
					this._anulacion_salida_por = value;
					this.SendPropertyChanged("anulacion_salida_por");
					this.Onanulacion_salida_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mercancia_salida", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> mercancia_salida
		{
			get
			{
				return this._mercancia_salida;
			}
			set
			{
				if ((this._mercancia_salida != value))
				{
					this.Onmercancia_salidaChanging(value);
					this.SendPropertyChanging();
					this._mercancia_salida = value;
					this.SendPropertyChanged("mercancia_salida");
					this.Onmercancia_salidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_salida_mercancia", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_salida_mercancia
		{
			get
			{
				return this._fecha_salida_mercancia;
			}
			set
			{
				if ((this._fecha_salida_mercancia != value))
				{
					this.Onfecha_salida_mercanciaChanging(value);
					this.SendPropertyChanging();
					this._fecha_salida_mercancia = value;
					this.SendPropertyChanged("fecha_salida_mercancia");
					this.Onfecha_salida_mercanciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_despachado_por", DbType="VarChar(100)")]
		public string despachado_por
		{
			get
			{
				return this._despachado_por;
			}
			set
			{
				if ((this._despachado_por != value))
				{
					this.Ondespachado_porChanging(value);
					this.SendPropertyChanging();
					this._despachado_por = value;
					this.SendPropertyChanged("despachado_por");
					this.Ondespachado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recargo", DbType="Money")]
		public System.Nullable<decimal> recargo
		{
			get
			{
				return this._recargo;
			}
			set
			{
				if ((this._recargo != value))
				{
					this.OnrecargoChanging(value);
					this.SendPropertyChanging();
					this._recargo = value;
					this.SendPropertyChanged("recargo");
					this.OnrecargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacion", DbType="VarChar(4000)")]
		public string observacion
		{
			get
			{
				return this._observacion;
			}
			set
			{
				if ((this._observacion != value))
				{
					this.OnobservacionChanging(value);
					this.SendPropertyChanging();
					this._observacion = value;
					this.SendPropertyChanged("observacion");
					this.OnobservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_entrega", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado_entrega
		{
			get
			{
				return this._estado_entrega;
			}
			set
			{
				if ((this._estado_entrega != value))
				{
					this.Onestado_entregaChanging(value);
					this.SendPropertyChanging();
					this._estado_entrega = value;
					this.SendPropertyChanged("estado_entrega");
					this.Onestado_entregaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forma_despacho", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> forma_despacho
		{
			get
			{
				return this._forma_despacho;
			}
			set
			{
				if ((this._forma_despacho != value))
				{
					this.Onforma_despachoChanging(value);
					this.SendPropertyChanging();
					this._forma_despacho = value;
					this.SendPropertyChanged("forma_despacho");
					this.Onforma_despachoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enviar_a", DbType="VarChar(200)")]
		public string enviar_a
		{
			get
			{
				return this._enviar_a;
			}
			set
			{
				if ((this._enviar_a != value))
				{
					this.Onenviar_aChanging(value);
					this.SendPropertyChanging();
					this._enviar_a = value;
					this.SendPropertyChanged("enviar_a");
					this.Onenviar_aChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(15)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_por", DbType="VarChar(15)")]
		public string modificado_por
		{
			get
			{
				return this._modificado_por;
			}
			set
			{
				if ((this._modificado_por != value))
				{
					this.Onmodificado_porChanging(value);
					this.SendPropertyChanging();
					this._modificado_por = value;
					this.SendPropertyChanged("modificado_por");
					this.Onmodificado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificado_el
		{
			get
			{
				return this._modificado_el;
			}
			set
			{
				if ((this._modificado_el != value))
				{
					this.Onmodificado_elChanging(value);
					this.SendPropertyChanging();
					this._modificado_el = value;
					this.SendPropertyChanged("modificado_el");
					this.Onmodificado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_cobro", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado_cobro
		{
			get
			{
				return this._estado_cobro;
			}
			set
			{
				if ((this._estado_cobro != value))
				{
					this.Onestado_cobroChanging(value);
					this.SendPropertyChanging();
					this._estado_cobro = value;
					this.SendPropertyChanged("estado_cobro");
					this.Onestado_cobroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cupon", DbType="VarChar(16)")]
		public string cupon
		{
			get
			{
				return this._cupon;
			}
			set
			{
				if ((this._cupon != value))
				{
					this.OncuponChanging(value);
					this.SendPropertyChanging();
					this._cupon = value;
					this.SendPropertyChanged("cupon");
					this.OncuponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioridad", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> prioridad
		{
			get
			{
				return this._prioridad;
			}
			set
			{
				if ((this._prioridad != value))
				{
					this.OnprioridadChanging(value);
					this.SendPropertyChanging();
					this._prioridad = value;
					this.SendPropertyChanged("prioridad");
					this.OnprioridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion_factura", DbType="VarChar(50)")]
		public string descripcion_factura
		{
			get
			{
				return this._descripcion_factura;
			}
			set
			{
				if ((this._descripcion_factura != value))
				{
					this.Ondescripcion_facturaChanging(value);
					this.SendPropertyChanging();
					this._descripcion_factura = value;
					this.SendPropertyChanged("descripcion_factura");
					this.Ondescripcion_facturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_monto_bruto_real", DbType="Money")]
		public System.Nullable<decimal> monto_bruto_real
		{
			get
			{
				return this._monto_bruto_real;
			}
			set
			{
				if ((this._monto_bruto_real != value))
				{
					this.Onmonto_bruto_realChanging(value);
					this.SendPropertyChanging();
					this._monto_bruto_real = value;
					this.SendPropertyChanged("monto_bruto_real");
					this.Onmonto_bruto_realChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_inventario", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_inventario
		{
			get
			{
				return this._cierre_inventario;
			}
			set
			{
				if ((this._cierre_inventario != value))
				{
					this.Oncierre_inventarioChanging(value);
					this.SendPropertyChanging();
					this._cierre_inventario = value;
					this.SendPropertyChanged("cierre_inventario");
					this.Oncierre_inventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias_atrasada", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dias_atrasada
		{
			get
			{
				return this._dias_atrasada;
			}
			set
			{
				if ((this._dias_atrasada != value))
				{
					this.Ondias_atrasadaChanging(value);
					this.SendPropertyChanging();
					this._dias_atrasada = value;
					this.SendPropertyChanged("dias_atrasada");
					this.Ondias_atrasadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimeraCuota", DbType="Money")]
		public System.Nullable<decimal> PrimeraCuota
		{
			get
			{
				return this._PrimeraCuota;
			}
			set
			{
				if ((this._PrimeraCuota != value))
				{
					this.OnPrimeraCuotaChanging(value);
					this.SendPropertyChanging();
					this._PrimeraCuota = value;
					this.SendPropertyChanged("PrimeraCuota");
					this.OnPrimeraCuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuotaMensual", DbType="Money")]
		public System.Nullable<decimal> CuotaMensual
		{
			get
			{
				return this._CuotaMensual;
			}
			set
			{
				if ((this._CuotaMensual != value))
				{
					this.OnCuotaMensualChanging(value);
					this.SendPropertyChanging();
					this._CuotaMensual = value;
					this.SendPropertyChanged("CuotaMensual");
					this.OnCuotaMensualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrdenOriginal", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> OrdenOriginal
		{
			get
			{
				return this._OrdenOriginal;
			}
			set
			{
				if ((this._OrdenOriginal != value))
				{
					this.OnOrdenOriginalChanging(value);
					this.SendPropertyChanging();
					this._OrdenOriginal = value;
					this.SendPropertyChanged("OrdenOriginal");
					this.OnOrdenOriginalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SolicitaEstudio", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> SolicitaEstudio
		{
			get
			{
				return this._SolicitaEstudio;
			}
			set
			{
				if ((this._SolicitaEstudio != value))
				{
					this.OnSolicitaEstudioChanging(value);
					this.SendPropertyChanging();
					this._SolicitaEstudio = value;
					this.SendPropertyChanged("SolicitaEstudio");
					this.OnSolicitaEstudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoEntregaInmediata", DbType="Money")]
		public System.Nullable<decimal> MontoEntregaInmediata
		{
			get
			{
				return this._MontoEntregaInmediata;
			}
			set
			{
				if ((this._MontoEntregaInmediata != value))
				{
					this.OnMontoEntregaInmediataChanging(value);
					this.SendPropertyChanging();
					this._MontoEntregaInmediata = value;
					this.SendPropertyChanged("MontoEntregaInmediata");
					this.OnMontoEntregaInmediataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postventa", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> postventa
		{
			get
			{
				return this._postventa;
			}
			set
			{
				if ((this._postventa != value))
				{
					this.OnpostventaChanging(value);
					this.SendPropertyChanging();
					this._postventa = value;
					this.SendPropertyChanged("postventa");
					this.OnpostventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_mercadeo", DbType="Decimal(2,0)")]
		public System.Nullable<decimal> plan_mercadeo
		{
			get
			{
				return this._plan_mercadeo;
			}
			set
			{
				if ((this._plan_mercadeo != value))
				{
					this.Onplan_mercadeoChanging(value);
					this.SendPropertyChanging();
					this._plan_mercadeo = value;
					this.SendPropertyChanged("plan_mercadeo");
					this.Onplan_mercadeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Verificada", DbType="Decimal(1,0)")]
		public System.Nullable<decimal> Verificada
		{
			get
			{
				return this._Verificada;
			}
			set
			{
				if ((this._Verificada != value))
				{
					this.OnVerificadaChanging(value);
					this.SendPropertyChanging();
					this._Verificada = value;
					this.SendPropertyChanged("Verificada");
					this.OnVerificadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_consecutivo", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal consecutivo
		{
			get
			{
				return this._consecutivo;
			}
			set
			{
				if ((this._consecutivo != value))
				{
					this.OnconsecutivoChanging(value);
					this.SendPropertyChanging();
					this._consecutivo = value;
					this.SendPropertyChanged("consecutivo");
					this.OnconsecutivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CierreCreacion", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> CierreCreacion
		{
			get
			{
				return this._CierreCreacion;
			}
			set
			{
				if ((this._CierreCreacion != value))
				{
					this.OnCierreCreacionChanging(value);
					this.SendPropertyChanging();
					this._CierreCreacion = value;
					this.SendPropertyChanged("CierreCreacion");
					this.OnCierreCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoLocalizacion", DbType="Money")]
		public System.Nullable<decimal> MontoLocalizacion
		{
			get
			{
				return this._MontoLocalizacion;
			}
			set
			{
				if ((this._MontoLocalizacion != value))
				{
					this.OnMontoLocalizacionChanging(value);
					this.SendPropertyChanging();
					this._MontoLocalizacion = value;
					this.SendPropertyChanged("MontoLocalizacion");
					this.OnMontoLocalizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deduccion_tarjeta", DbType="Int")]
		public System.Nullable<int> deduccion_tarjeta
		{
			get
			{
				return this._deduccion_tarjeta;
			}
			set
			{
				if ((this._deduccion_tarjeta != value))
				{
					this.Ondeduccion_tarjetaChanging(value);
					this.SendPropertyChanging();
					this._deduccion_tarjeta = value;
					this.SendPropertyChanged("deduccion_tarjeta");
					this.Ondeduccion_tarjetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_actualizada", DbType="Int")]
		public System.Nullable<int> actualizada
		{
			get
			{
				return this._actualizada;
			}
			set
			{
				if ((this._actualizada != value))
				{
					this.OnactualizadaChanging(value);
					this.SendPropertyChanging();
					this._actualizada = value;
					this.SendPropertyChanged("actualizada");
					this.OnactualizadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insertada", DbType="Int")]
		public System.Nullable<int> insertada
		{
			get
			{
				return this._insertada;
			}
			set
			{
				if ((this._insertada != value))
				{
					this.OninsertadaChanging(value);
					this.SendPropertyChanging();
					this._insertada = value;
					this.SendPropertyChanged("insertada");
					this.OninsertadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ref", Storage="_ref", DbType="VarChar(50)")]
		public string @ref
		{
			get
			{
				return this._ref;
			}
			set
			{
				if ((this._ref != value))
				{
					this.OnrefChanging(value);
					this.SendPropertyChanging();
					this._ref = value;
					this.SendPropertyChanged("@ref");
					this.OnrefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntregaInmediata", DbType="Int")]
		public System.Nullable<int> EntregaInmediata
		{
			get
			{
				return this._EntregaInmediata;
			}
			set
			{
				if ((this._EntregaInmediata != value))
				{
					this.OnEntregaInmediataChanging(value);
					this.SendPropertyChanging();
					this._EntregaInmediata = value;
					this.SendPropertyChanged("EntregaInmediata");
					this.OnEntregaInmediataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reclasificacion", DbType="Int")]
		public System.Nullable<int> Reclasificacion
		{
			get
			{
				return this._Reclasificacion;
			}
			set
			{
				if ((this._Reclasificacion != value))
				{
					this.OnReclasificacionChanging(value);
					this.SendPropertyChanging();
					this._Reclasificacion = value;
					this.SendPropertyChanged("Reclasificacion");
					this.OnReclasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuotasReclasificacion", DbType="Int")]
		public System.Nullable<int> CuotasReclasificacion
		{
			get
			{
				return this._CuotasReclasificacion;
			}
			set
			{
				if ((this._CuotasReclasificacion != value))
				{
					this.OnCuotasReclasificacionChanging(value);
					this.SendPropertyChanging();
					this._CuotasReclasificacion = value;
					this.SendPropertyChanged("CuotasReclasificacion");
					this.OnCuotasReclasificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="cliente_factura", Storage="_cliente1", ThisKey="cliente", OtherKey="cliente1", IsForeignKey=true)]
		public cliente cliente1
		{
			get
			{
				return this._cliente1.Entity;
			}
			set
			{
				cliente previousValue = this._cliente1.Entity;
				if (((previousValue != value) 
							|| (this._cliente1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._cliente1.Entity = null;
						previousValue.facturas.Remove(this);
					}
					this._cliente1.Entity = value;
					if ((value != null))
					{
						value.facturas.Add(this);
						this._cliente = value.cliente1;
					}
					else
					{
						this._cliente = default(string);
					}
					this.SendPropertyChanged("cliente1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
