#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrosDeVenta
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sakif")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRegistroTemp(RegistroTemp instance);
    partial void UpdateRegistroTemp(RegistroTemp instance);
    partial void DeleteRegistroTemp(RegistroTemp instance);
    #endregion
		
		public dbDataContext() : 
				base(global::RegistrosDeVenta.Properties.Settings.Default.SakifConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<RegistroTemp> RegistroTemps
		{
			get
			{
				return this.GetTable<RegistroTemp>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ventas_informe")]
	public partial class RegistroTemp : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _vendedor;
		
		private System.Nullable<decimal> _cierre;
		
		private System.Nullable<decimal> _venta;
		
		private System.Nullable<decimal> _venta_generacion;
		
		private System.Nullable<int> _nuevos_reclutas;
		
		private System.Nullable<int> _activos_directos;
		
		private System.Nullable<int> _activos_indirectos;
		
		private System.Nullable<int> _conventa_directos;
		
		private System.Nullable<int> _conventa_indirectos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void OncierreChanging(System.Nullable<decimal> value);
    partial void OncierreChanged();
    partial void OnventaChanging(System.Nullable<decimal> value);
    partial void OnventaChanged();
    partial void Onventa_generacionChanging(System.Nullable<decimal> value);
    partial void Onventa_generacionChanged();
    partial void Onnuevos_reclutasChanging(System.Nullable<int> value);
    partial void Onnuevos_reclutasChanged();
    partial void Onactivos_directosChanging(System.Nullable<int> value);
    partial void Onactivos_directosChanged();
    partial void Onactivos_indirectosChanging(System.Nullable<int> value);
    partial void Onactivos_indirectosChanged();
    partial void Onconventa_directosChanging(System.Nullable<int> value);
    partial void Onconventa_directosChanged();
    partial void Onconventa_indirectosChanging(System.Nullable<int> value);
    partial void Onconventa_indirectosChanged();
    #endregion
		
		public RegistroTemp()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre
		{
			get
			{
				return this._cierre;
			}
			set
			{
				if ((this._cierre != value))
				{
					this.OncierreChanging(value);
					this.SendPropertyChanging();
					this._cierre = value;
					this.SendPropertyChanged("cierre");
					this.OncierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venta", DbType="Money")]
		public System.Nullable<decimal> venta
		{
			get
			{
				return this._venta;
			}
			set
			{
				if ((this._venta != value))
				{
					this.OnventaChanging(value);
					this.SendPropertyChanging();
					this._venta = value;
					this.SendPropertyChanged("venta");
					this.OnventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venta_generacion", DbType="Money")]
		public System.Nullable<decimal> venta_generacion
		{
			get
			{
				return this._venta_generacion;
			}
			set
			{
				if ((this._venta_generacion != value))
				{
					this.Onventa_generacionChanging(value);
					this.SendPropertyChanging();
					this._venta_generacion = value;
					this.SendPropertyChanged("venta_generacion");
					this.Onventa_generacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nuevos_reclutas", DbType="Int")]
		public System.Nullable<int> nuevos_reclutas
		{
			get
			{
				return this._nuevos_reclutas;
			}
			set
			{
				if ((this._nuevos_reclutas != value))
				{
					this.Onnuevos_reclutasChanging(value);
					this.SendPropertyChanging();
					this._nuevos_reclutas = value;
					this.SendPropertyChanged("nuevos_reclutas");
					this.Onnuevos_reclutasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activos_directos", DbType="Int")]
		public System.Nullable<int> activos_directos
		{
			get
			{
				return this._activos_directos;
			}
			set
			{
				if ((this._activos_directos != value))
				{
					this.Onactivos_directosChanging(value);
					this.SendPropertyChanging();
					this._activos_directos = value;
					this.SendPropertyChanged("activos_directos");
					this.Onactivos_directosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activos_indirectos", DbType="Int")]
		public System.Nullable<int> activos_indirectos
		{
			get
			{
				return this._activos_indirectos;
			}
			set
			{
				if ((this._activos_indirectos != value))
				{
					this.Onactivos_indirectosChanging(value);
					this.SendPropertyChanging();
					this._activos_indirectos = value;
					this.SendPropertyChanged("activos_indirectos");
					this.Onactivos_indirectosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conventa_directos", DbType="Int")]
		public System.Nullable<int> conventa_directos
		{
			get
			{
				return this._conventa_directos;
			}
			set
			{
				if ((this._conventa_directos != value))
				{
					this.Onconventa_directosChanging(value);
					this.SendPropertyChanging();
					this._conventa_directos = value;
					this.SendPropertyChanged("conventa_directos");
					this.Onconventa_directosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conventa_indirectos", DbType="Int")]
		public System.Nullable<int> conventa_indirectos
		{
			get
			{
				return this._conventa_indirectos;
			}
			set
			{
				if ((this._conventa_indirectos != value))
				{
					this.Onconventa_indirectosChanging(value);
					this.SendPropertyChanging();
					this._conventa_indirectos = value;
					this.SendPropertyChanged("conventa_indirectos");
					this.Onconventa_indirectosChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
