#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clientes.DataLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sakif")]
	public partial class dbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcliente(cliente instance);
    partial void Updatecliente(cliente instance);
    partial void Deletecliente(cliente instance);
    partial void Inserttiposcliente(tiposcliente instance);
    partial void Updatetiposcliente(tiposcliente instance);
    partial void Deletetiposcliente(tiposcliente instance);
    #endregion
		
		public dbDataContext() : 
				base(global::Clientes.Properties.Settings.Default.SakifConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<cliente> clientes
		{
			get
			{
				return this.GetTable<cliente>();
			}
		}
		
		public System.Data.Linq.Table<tiposcliente> tiposclientes
		{
			get
			{
				return this.GetTable<tiposcliente>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.clientes")]
	public partial class cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _id;
		
		private string _nombre;
		
		private string _apellido_01;
		
		private string _apellido_02;
		
		private decimal _IDtipoCliente;
		
		private string _zona;
		
		private string _tipo_de_identificacion;
		
		private decimal _estado;
		
		private System.Nullable<decimal> _provincia;
		
		private System.Nullable<decimal> _canton;
		
		private System.Nullable<decimal> _distrito;
		
		private System.Nullable<decimal> _Barrio;
		
		private string _identificacion;
		
		private string _descripcion;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private string _direccion;
		
		private string _telefono_01;
		
		private string _telefono_02;
		
		private string _telefono_03;
		
		private string _fax;
		
		private string _email;
		
		private string _representante;
		
		private System.Nullable<decimal> _limite_de_credito;
		
		private System.Nullable<decimal> _descuento_general;
		
		private System.Nullable<decimal> _dias_plazo;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _modificado_por;
		
		private System.Nullable<System.DateTime> _modificado_el;
		
		private string _vendedor;
		
		private System.Nullable<int> _acepta_impuesto;
		
		private string _observaciones;
		
		private System.Nullable<int> _mostrar_obs_fact;
		
		private System.Nullable<decimal> _compania;
		
		private System.Nullable<decimal> _animo;
		
		private string _correo_actualizado_por;
		
		private System.Nullable<System.DateTime> _correo_actualizado_el;
		
		private string _correo_anterior;
		
		private System.Nullable<int> _CedulaCorrecta;
		
		private System.Nullable<decimal> _venta_mes_anterior;
		
		private System.Nullable<decimal> _saldo_vendido;
		
		private EntityRef<tiposcliente> _tipocliente;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onapellido_01Changing(string value);
    partial void Onapellido_01Changed();
    partial void Onapellido_02Changing(string value);
    partial void Onapellido_02Changed();
    partial void OnIDtipoClienteChanging(decimal value);
    partial void OnIDtipoClienteChanged();
    partial void OnzonaChanging(string value);
    partial void OnzonaChanged();
    partial void Ontipo_de_identificacionChanging(string value);
    partial void Ontipo_de_identificacionChanged();
    partial void OnestadoChanging(decimal value);
    partial void OnestadoChanged();
    partial void OnprovinciaChanging(System.Nullable<decimal> value);
    partial void OnprovinciaChanged();
    partial void OncantonChanging(System.Nullable<decimal> value);
    partial void OncantonChanged();
    partial void OndistritoChanging(System.Nullable<decimal> value);
    partial void OndistritoChanged();
    partial void OnBarrioChanging(System.Nullable<decimal> value);
    partial void OnBarrioChanged();
    partial void OnidentificacionChanging(string value);
    partial void OnidentificacionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void Ontelefono_01Changing(string value);
    partial void Ontelefono_01Changed();
    partial void Ontelefono_02Changing(string value);
    partial void Ontelefono_02Changed();
    partial void Ontelefono_03Changing(string value);
    partial void Ontelefono_03Changed();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnrepresentanteChanging(string value);
    partial void OnrepresentanteChanged();
    partial void Onlimite_de_creditoChanging(System.Nullable<decimal> value);
    partial void Onlimite_de_creditoChanged();
    partial void Ondescuento_generalChanging(System.Nullable<decimal> value);
    partial void Ondescuento_generalChanged();
    partial void Ondias_plazoChanging(System.Nullable<decimal> value);
    partial void Ondias_plazoChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Onmodificado_porChanging(string value);
    partial void Onmodificado_porChanged();
    partial void Onmodificado_elChanging(System.Nullable<System.DateTime> value);
    partial void Onmodificado_elChanged();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void Onacepta_impuestoChanging(System.Nullable<int> value);
    partial void Onacepta_impuestoChanged();
    partial void OnobservacionesChanging(string value);
    partial void OnobservacionesChanged();
    partial void Onmostrar_obs_factChanging(System.Nullable<int> value);
    partial void Onmostrar_obs_factChanged();
    partial void OncompaniaChanging(System.Nullable<decimal> value);
    partial void OncompaniaChanged();
    partial void OnanimoChanging(System.Nullable<decimal> value);
    partial void OnanimoChanged();
    partial void Oncorreo_actualizado_porChanging(string value);
    partial void Oncorreo_actualizado_porChanged();
    partial void Oncorreo_actualizado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncorreo_actualizado_elChanged();
    partial void Oncorreo_anteriorChanging(string value);
    partial void Oncorreo_anteriorChanged();
    partial void OnCedulaCorrectaChanging(System.Nullable<int> value);
    partial void OnCedulaCorrectaChanged();
    partial void Onventa_mes_anteriorChanging(System.Nullable<decimal> value);
    partial void Onventa_mes_anteriorChanged();
    partial void Onsaldo_vendidoChanging(System.Nullable<decimal> value);
    partial void Onsaldo_vendidoChanged();
    #endregion
		
		public cliente()
		{
			this._tipocliente = default(EntityRef<tiposcliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cliente", Storage="_id", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_01", DbType="VarChar(255)")]
		public string apellido_01
		{
			get
			{
				return this._apellido_01;
			}
			set
			{
				if ((this._apellido_01 != value))
				{
					this.Onapellido_01Changing(value);
					this.SendPropertyChanging();
					this._apellido_01 = value;
					this.SendPropertyChanged("apellido_01");
					this.Onapellido_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_02", DbType="VarChar(255)")]
		public string apellido_02
		{
			get
			{
				return this._apellido_02;
			}
			set
			{
				if ((this._apellido_02 != value))
				{
					this.Onapellido_02Changing(value);
					this.SendPropertyChanging();
					this._apellido_02 = value;
					this.SendPropertyChanged("apellido_02");
					this.Onapellido_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="tipo", Storage="_IDtipoCliente", DbType="Decimal(18,0) NOT NULL")]
		public decimal IDtipoCliente
		{
			get
			{
				return this._IDtipoCliente;
			}
			set
			{
				if ((this._IDtipoCliente != value))
				{
					this.OnIDtipoClienteChanging(value);
					this.SendPropertyChanging();
					this._IDtipoCliente = value;
					this.SendPropertyChanged("IDtipoCliente");
					this.OnIDtipoClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				if ((this._zona != value))
				{
					this.OnzonaChanging(value);
					this.SendPropertyChanging();
					this._zona = value;
					this.SendPropertyChanged("zona");
					this.OnzonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_de_identificacion", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string tipo_de_identificacion
		{
			get
			{
				return this._tipo_de_identificacion;
			}
			set
			{
				if ((this._tipo_de_identificacion != value))
				{
					this.Ontipo_de_identificacionChanging(value);
					this.SendPropertyChanging();
					this._tipo_de_identificacion = value;
					this.SendPropertyChanged("tipo_de_identificacion");
					this.Ontipo_de_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Decimal(4,0) NOT NULL")]
		public decimal estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this.OnprovinciaChanging(value);
					this.SendPropertyChanging();
					this._provincia = value;
					this.SendPropertyChanged("provincia");
					this.OnprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this.OncantonChanging(value);
					this.SendPropertyChanging();
					this._canton = value;
					this.SendPropertyChanged("canton");
					this.OncantonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this.OndistritoChanging(value);
					this.SendPropertyChanging();
					this._distrito = value;
					this.SendPropertyChanged("distrito");
					this.OndistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barrio", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Barrio
		{
			get
			{
				return this._Barrio;
			}
			set
			{
				if ((this._Barrio != value))
				{
					this.OnBarrioChanging(value);
					this.SendPropertyChanging();
					this._Barrio = value;
					this.SendPropertyChanged("Barrio");
					this.OnBarrioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificacion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string identificacion
		{
			get
			{
				return this._identificacion;
			}
			set
			{
				if ((this._identificacion != value))
				{
					this.OnidentificacionChanging(value);
					this.SendPropertyChanging();
					this._identificacion = value;
					this.SendPropertyChanged("identificacion");
					this.OnidentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(255)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_01", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono_01
		{
			get
			{
				return this._telefono_01;
			}
			set
			{
				if ((this._telefono_01 != value))
				{
					this.Ontelefono_01Changing(value);
					this.SendPropertyChanging();
					this._telefono_01 = value;
					this.SendPropertyChanged("telefono_01");
					this.Ontelefono_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_02", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string telefono_02
		{
			get
			{
				return this._telefono_02;
			}
			set
			{
				if ((this._telefono_02 != value))
				{
					this.Ontelefono_02Changing(value);
					this.SendPropertyChanging();
					this._telefono_02 = value;
					this.SendPropertyChanged("telefono_02");
					this.Ontelefono_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_03", DbType="VarChar(50)")]
		public string telefono_03
		{
			get
			{
				return this._telefono_03;
			}
			set
			{
				if ((this._telefono_03 != value))
				{
					this.Ontelefono_03Changing(value);
					this.SendPropertyChanging();
					this._telefono_03 = value;
					this.SendPropertyChanged("telefono_03");
					this.Ontelefono_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_representante", DbType="VarChar(100)")]
		public string representante
		{
			get
			{
				return this._representante;
			}
			set
			{
				if ((this._representante != value))
				{
					this.OnrepresentanteChanging(value);
					this.SendPropertyChanging();
					this._representante = value;
					this.SendPropertyChanged("representante");
					this.OnrepresentanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_limite_de_credito", DbType="Money")]
		public System.Nullable<decimal> limite_de_credito
		{
			get
			{
				return this._limite_de_credito;
			}
			set
			{
				if ((this._limite_de_credito != value))
				{
					this.Onlimite_de_creditoChanging(value);
					this.SendPropertyChanging();
					this._limite_de_credito = value;
					this.SendPropertyChanged("limite_de_credito");
					this.Onlimite_de_creditoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento_general", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> descuento_general
		{
			get
			{
				return this._descuento_general;
			}
			set
			{
				if ((this._descuento_general != value))
				{
					this.Ondescuento_generalChanging(value);
					this.SendPropertyChanging();
					this._descuento_general = value;
					this.SendPropertyChanged("descuento_general");
					this.Ondescuento_generalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dias_plazo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> dias_plazo
		{
			get
			{
				return this._dias_plazo;
			}
			set
			{
				if ((this._dias_plazo != value))
				{
					this.Ondias_plazoChanging(value);
					this.SendPropertyChanging();
					this._dias_plazo = value;
					this.SendPropertyChanged("dias_plazo");
					this.Ondias_plazoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(255)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_por", DbType="VarChar(255)")]
		public string modificado_por
		{
			get
			{
				return this._modificado_por;
			}
			set
			{
				if ((this._modificado_por != value))
				{
					this.Onmodificado_porChanging(value);
					this.SendPropertyChanging();
					this._modificado_por = value;
					this.SendPropertyChanged("modificado_por");
					this.Onmodificado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificado_el
		{
			get
			{
				return this._modificado_el;
			}
			set
			{
				if ((this._modificado_el != value))
				{
					this.Onmodificado_elChanging(value);
					this.SendPropertyChanging();
					this._modificado_el = value;
					this.SendPropertyChanged("modificado_el");
					this.Onmodificado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(30)")]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acepta_impuesto", DbType="Int")]
		public System.Nullable<int> acepta_impuesto
		{
			get
			{
				return this._acepta_impuesto;
			}
			set
			{
				if ((this._acepta_impuesto != value))
				{
					this.Onacepta_impuestoChanging(value);
					this.SendPropertyChanging();
					this._acepta_impuesto = value;
					this.SendPropertyChanged("acepta_impuesto");
					this.Onacepta_impuestoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observaciones", DbType="VarChar(500)")]
		public string observaciones
		{
			get
			{
				return this._observaciones;
			}
			set
			{
				if ((this._observaciones != value))
				{
					this.OnobservacionesChanging(value);
					this.SendPropertyChanging();
					this._observaciones = value;
					this.SendPropertyChanged("observaciones");
					this.OnobservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostrar_obs_fact", DbType="Int")]
		public System.Nullable<int> mostrar_obs_fact
		{
			get
			{
				return this._mostrar_obs_fact;
			}
			set
			{
				if ((this._mostrar_obs_fact != value))
				{
					this.Onmostrar_obs_factChanging(value);
					this.SendPropertyChanging();
					this._mostrar_obs_fact = value;
					this.SendPropertyChanged("mostrar_obs_fact");
					this.Onmostrar_obs_factChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compania", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> compania
		{
			get
			{
				return this._compania;
			}
			set
			{
				if ((this._compania != value))
				{
					this.OncompaniaChanging(value);
					this.SendPropertyChanging();
					this._compania = value;
					this.SendPropertyChanged("compania");
					this.OncompaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_animo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> animo
		{
			get
			{
				return this._animo;
			}
			set
			{
				if ((this._animo != value))
				{
					this.OnanimoChanging(value);
					this.SendPropertyChanging();
					this._animo = value;
					this.SendPropertyChanged("animo");
					this.OnanimoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_actualizado_por", DbType="VarChar(50)")]
		public string correo_actualizado_por
		{
			get
			{
				return this._correo_actualizado_por;
			}
			set
			{
				if ((this._correo_actualizado_por != value))
				{
					this.Oncorreo_actualizado_porChanging(value);
					this.SendPropertyChanging();
					this._correo_actualizado_por = value;
					this.SendPropertyChanged("correo_actualizado_por");
					this.Oncorreo_actualizado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_actualizado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> correo_actualizado_el
		{
			get
			{
				return this._correo_actualizado_el;
			}
			set
			{
				if ((this._correo_actualizado_el != value))
				{
					this.Oncorreo_actualizado_elChanging(value);
					this.SendPropertyChanging();
					this._correo_actualizado_el = value;
					this.SendPropertyChanged("correo_actualizado_el");
					this.Oncorreo_actualizado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo_anterior", DbType="VarChar(200)")]
		public string correo_anterior
		{
			get
			{
				return this._correo_anterior;
			}
			set
			{
				if ((this._correo_anterior != value))
				{
					this.Oncorreo_anteriorChanging(value);
					this.SendPropertyChanging();
					this._correo_anterior = value;
					this.SendPropertyChanged("correo_anterior");
					this.Oncorreo_anteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CedulaCorrecta", DbType="Int")]
		public System.Nullable<int> CedulaCorrecta
		{
			get
			{
				return this._CedulaCorrecta;
			}
			set
			{
				if ((this._CedulaCorrecta != value))
				{
					this.OnCedulaCorrectaChanging(value);
					this.SendPropertyChanging();
					this._CedulaCorrecta = value;
					this.SendPropertyChanged("CedulaCorrecta");
					this.OnCedulaCorrectaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venta_mes_anterior", DbType="Money")]
		public System.Nullable<decimal> venta_mes_anterior
		{
			get
			{
				return this._venta_mes_anterior;
			}
			set
			{
				if ((this._venta_mes_anterior != value))
				{
					this.Onventa_mes_anteriorChanging(value);
					this.SendPropertyChanging();
					this._venta_mes_anterior = value;
					this.SendPropertyChanged("venta_mes_anterior");
					this.Onventa_mes_anteriorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saldo_vendido", DbType="Money")]
		public System.Nullable<decimal> saldo_vendido
		{
			get
			{
				return this._saldo_vendido;
			}
			set
			{
				if ((this._saldo_vendido != value))
				{
					this.Onsaldo_vendidoChanging(value);
					this.SendPropertyChanging();
					this._saldo_vendido = value;
					this.SendPropertyChanged("saldo_vendido");
					this.Onsaldo_vendidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipos_de_cliente_cliente", Storage="_tipocliente", ThisKey="IDtipoCliente", OtherKey="tipo", IsForeignKey=true)]
		public tiposcliente tipocliente
		{
			get
			{
				return this._tipocliente.Entity;
			}
			set
			{
				tiposcliente previousValue = this._tipocliente.Entity;
				if (((previousValue != value) 
							|| (this._tipocliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tipocliente.Entity = null;
						previousValue.clientes.Remove(this);
					}
					this._tipocliente.Entity = value;
					if ((value != null))
					{
						value.clientes.Add(this);
						this._IDtipoCliente = value.tipo;
					}
					else
					{
						this._IDtipoCliente = default(decimal);
					}
					this.SendPropertyChanged("tipocliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipos_de_cliente")]
	public partial class tiposcliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _tipo;
		
		private string _descripcion;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _modificado_por;
		
		private System.Nullable<System.DateTime> _modificado_el;
		
		private EntitySet<cliente> _clientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntipoChanging(decimal value);
    partial void OntipoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Onmodificado_porChanging(string value);
    partial void Onmodificado_porChanged();
    partial void Onmodificado_elChanging(System.Nullable<System.DateTime> value);
    partial void Onmodificado_elChanged();
    #endregion
		
		public tiposcliente()
		{
			this._clientes = new EntitySet<cliente>(new Action<cliente>(this.attach_clientes), new Action<cliente>(this.detach_clientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(15)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_por", DbType="VarChar(15)")]
		public string modificado_por
		{
			get
			{
				return this._modificado_por;
			}
			set
			{
				if ((this._modificado_por != value))
				{
					this.Onmodificado_porChanging(value);
					this.SendPropertyChanging();
					this._modificado_por = value;
					this.SendPropertyChanged("modificado_por");
					this.Onmodificado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificado_el
		{
			get
			{
				return this._modificado_el;
			}
			set
			{
				if ((this._modificado_el != value))
				{
					this.Onmodificado_elChanging(value);
					this.SendPropertyChanging();
					this._modificado_el = value;
					this.SendPropertyChanged("modificado_el");
					this.Onmodificado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipos_de_cliente_cliente", Storage="_clientes", ThisKey="tipo", OtherKey="IDtipoCliente")]
		public EntitySet<cliente> clientes
		{
			get
			{
				return this._clientes;
			}
			set
			{
				this._clientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.tipocliente = this;
		}
		
		private void detach_clientes(cliente entity)
		{
			this.SendPropertyChanging();
			entity.tipocliente = null;
		}
	}
}
#pragma warning restore 1591
