<?xml version="1.0" encoding="utf-8"?><Database Name="Sakif" Class="DataBaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.0.2;Initial Catalog=Sakif;User ID=sa" SettingsObjectName="Concursos.Properties.Settings" SettingsPropertyName="SakifConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Concursos" Member="Concursos">
    <Type Name="Concurso">
      <Column Name="id_concurso" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="PeriodoInicio" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PeriodoCierre" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="VentaPersonal" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="VentaEquipo" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Puntos" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="estado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>