#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concursos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sakif")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertConcurso(Concurso instance);
    partial void UpdateConcurso(Concurso instance);
    partial void DeleteConcurso(Concurso instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::Concursos.Properties.Settings.Default.SakifConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Concurso> Concursos
		{
			get
			{
				return this.GetTable<Concurso>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Concursos")]
	public partial class Concurso : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_concurso;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _PeriodoInicio;
		
		private System.Nullable<decimal> _PeriodoCierre;
		
		private System.Nullable<decimal> _VentaPersonal;
		
		private System.Nullable<decimal> _VentaEquipo;
		
		private System.Nullable<decimal> _Puntos;
		
		private System.Nullable<decimal> _estado;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_concursoChanging(decimal value);
    partial void Onid_concursoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnPeriodoInicioChanging(System.Nullable<decimal> value);
    partial void OnPeriodoInicioChanged();
    partial void OnPeriodoCierreChanging(System.Nullable<decimal> value);
    partial void OnPeriodoCierreChanged();
    partial void OnVentaPersonalChanging(System.Nullable<decimal> value);
    partial void OnVentaPersonalChanged();
    partial void OnVentaEquipoChanging(System.Nullable<decimal> value);
    partial void OnVentaEquipoChanged();
    partial void OnPuntosChanging(System.Nullable<decimal> value);
    partial void OnPuntosChanged();
    partial void OnestadoChanging(System.Nullable<decimal> value);
    partial void OnestadoChanged();
    #endregion
		
		public Concurso()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_concurso", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_concurso
		{
			get
			{
				return this._id_concurso;
			}
			set
			{
				if ((this._id_concurso != value))
				{
					this.Onid_concursoChanging(value);
					this.SendPropertyChanging();
					this._id_concurso = value;
					this.SendPropertyChanged("id_concurso");
					this.Onid_concursoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(250)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoInicio", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PeriodoInicio
		{
			get
			{
				return this._PeriodoInicio;
			}
			set
			{
				if ((this._PeriodoInicio != value))
				{
					this.OnPeriodoInicioChanging(value);
					this.SendPropertyChanging();
					this._PeriodoInicio = value;
					this.SendPropertyChanged("PeriodoInicio");
					this.OnPeriodoInicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PeriodoCierre", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PeriodoCierre
		{
			get
			{
				return this._PeriodoCierre;
			}
			set
			{
				if ((this._PeriodoCierre != value))
				{
					this.OnPeriodoCierreChanging(value);
					this.SendPropertyChanging();
					this._PeriodoCierre = value;
					this.SendPropertyChanged("PeriodoCierre");
					this.OnPeriodoCierreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaPersonal", DbType="Money")]
		public System.Nullable<decimal> VentaPersonal
		{
			get
			{
				return this._VentaPersonal;
			}
			set
			{
				if ((this._VentaPersonal != value))
				{
					this.OnVentaPersonalChanging(value);
					this.SendPropertyChanging();
					this._VentaPersonal = value;
					this.SendPropertyChanged("VentaPersonal");
					this.OnVentaPersonalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VentaEquipo", DbType="Money")]
		public System.Nullable<decimal> VentaEquipo
		{
			get
			{
				return this._VentaEquipo;
			}
			set
			{
				if ((this._VentaEquipo != value))
				{
					this.OnVentaEquipoChanging(value);
					this.SendPropertyChanging();
					this._VentaEquipo = value;
					this.SendPropertyChanged("VentaEquipo");
					this.OnVentaEquipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Puntos", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Puntos
		{
			get
			{
				return this._Puntos;
			}
			set
			{
				if ((this._Puntos != value))
				{
					this.OnPuntosChanging(value);
					this.SendPropertyChanging();
					this._Puntos = value;
					this.SendPropertyChanged("Puntos");
					this.OnPuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
