#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Academic.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sakif")]
	public partial class DataMapDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCapacitacion(Capacitacion instance);
    partial void UpdateCapacitacion(Capacitacion instance);
    partial void DeleteCapacitacion(Capacitacion instance);
    partial void InsertCapacitacion_modulo(Capacitacion_modulo instance);
    partial void UpdateCapacitacion_modulo(Capacitacion_modulo instance);
    partial void DeleteCapacitacion_modulo(Capacitacion_modulo instance);
    partial void Insertcapacitacion_modulos_vendedore(capacitacion_modulos_vendedore instance);
    partial void Updatecapacitacion_modulos_vendedore(capacitacion_modulos_vendedore instance);
    partial void Deletecapacitacion_modulos_vendedore(capacitacion_modulos_vendedore instance);
    partial void Insertvendedore(vendedore instance);
    partial void Updatevendedore(vendedore instance);
    partial void Deletevendedore(vendedore instance);
    #endregion
		
		public DataMapDataContext() : 
				base(global::Academic.DataAccess.Properties.Settings.Default.SakifConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataMapDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMapDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMapDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMapDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Capacitacion> Capacitacions
		{
			get
			{
				return this.GetTable<Capacitacion>();
			}
		}
		
		public System.Data.Linq.Table<Capacitacion_modulo> Capacitacion_modulos
		{
			get
			{
				return this.GetTable<Capacitacion_modulo>();
			}
		}
		
		public System.Data.Linq.Table<capacitacion_modulos_vendedore> capacitacion_modulos_vendedores
		{
			get
			{
				return this.GetTable<capacitacion_modulos_vendedore>();
			}
		}
		
		public System.Data.Linq.Table<vendedore> vendedores
		{
			get
			{
				return this.GetTable<vendedore>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Capacitaciones")]
	public partial class Capacitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id;
		
		private string _descripcion;
		
		private EntitySet<Capacitacion_modulo> _Capacitacion_modulos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Capacitacion()
		{
			this._Capacitacion_modulos = new EntitySet<Capacitacion_modulo>(new Action<Capacitacion_modulo>(this.attach_Capacitacion_modulos), new Action<Capacitacion_modulo>(this.detach_Capacitacion_modulos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(18,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(150)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Capacitacion_Capacitacion_modulo", Storage="_Capacitacion_modulos", ThisKey="id", OtherKey="id_capacitacion")]
		public EntitySet<Capacitacion_modulo> Capacitacion_modulos
		{
			get
			{
				return this._Capacitacion_modulos;
			}
			set
			{
				this._Capacitacion_modulos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Capacitacion_modulos(Capacitacion_modulo entity)
		{
			this.SendPropertyChanging();
			entity.Capacitacion = this;
		}
		
		private void detach_Capacitacion_modulos(Capacitacion_modulo entity)
		{
			this.SendPropertyChanging();
			entity.Capacitacion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Capacitacion_modulos")]
	public partial class Capacitacion_modulo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_capacitacion;
		
		private decimal _id_modulo;
		
		private System.Nullable<int> _prioridad;
		
		private string _nombre;
		
		private string _descripcion;
		
		private EntitySet<capacitacion_modulos_vendedore> _capacitacion_modulos_vendedores;
		
		private EntityRef<Capacitacion> _Capacitacion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_capacitacionChanging(decimal value);
    partial void Onid_capacitacionChanged();
    partial void Onid_moduloChanging(decimal value);
    partial void Onid_moduloChanged();
    partial void OnprioridadChanging(System.Nullable<int> value);
    partial void OnprioridadChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public Capacitacion_modulo()
		{
			this._capacitacion_modulos_vendedores = new EntitySet<capacitacion_modulos_vendedore>(new Action<capacitacion_modulos_vendedore>(this.attach_capacitacion_modulos_vendedores), new Action<capacitacion_modulos_vendedore>(this.detach_capacitacion_modulos_vendedores));
			this._Capacitacion = default(EntityRef<Capacitacion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_capacitacion", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_capacitacion
		{
			get
			{
				return this._id_capacitacion;
			}
			set
			{
				if ((this._id_capacitacion != value))
				{
					if (this._Capacitacion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_capacitacionChanging(value);
					this.SendPropertyChanging();
					this._id_capacitacion = value;
					this.SendPropertyChanged("id_capacitacion");
					this.Onid_capacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_modulo", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_modulo
		{
			get
			{
				return this._id_modulo;
			}
			set
			{
				if ((this._id_modulo != value))
				{
					this.Onid_moduloChanging(value);
					this.SendPropertyChanging();
					this._id_modulo = value;
					this.SendPropertyChanged("id_modulo");
					this.Onid_moduloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prioridad", DbType="Int")]
		public System.Nullable<int> prioridad
		{
			get
			{
				return this._prioridad;
			}
			set
			{
				if ((this._prioridad != value))
				{
					this.OnprioridadChanging(value);
					this.SendPropertyChanging();
					this._prioridad = value;
					this.SendPropertyChanged("prioridad");
					this.OnprioridadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(150)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(150)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Capacitacion_modulo_capacitacion_modulos_vendedore", Storage="_capacitacion_modulos_vendedores", ThisKey="id_capacitacion,id_modulo", OtherKey="id_capacitacion,id_modulo")]
		public EntitySet<capacitacion_modulos_vendedore> capacitacion_modulos_vendedores
		{
			get
			{
				return this._capacitacion_modulos_vendedores;
			}
			set
			{
				this._capacitacion_modulos_vendedores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Capacitacion_Capacitacion_modulo", Storage="_Capacitacion", ThisKey="id_capacitacion", OtherKey="id", IsForeignKey=true)]
		public Capacitacion Capacitacion
		{
			get
			{
				return this._Capacitacion.Entity;
			}
			set
			{
				Capacitacion previousValue = this._Capacitacion.Entity;
				if (((previousValue != value) 
							|| (this._Capacitacion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Capacitacion.Entity = null;
						previousValue.Capacitacion_modulos.Remove(this);
					}
					this._Capacitacion.Entity = value;
					if ((value != null))
					{
						value.Capacitacion_modulos.Add(this);
						this._id_capacitacion = value.id;
					}
					else
					{
						this._id_capacitacion = default(decimal);
					}
					this.SendPropertyChanged("Capacitacion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_capacitacion_modulos_vendedores(capacitacion_modulos_vendedore entity)
		{
			this.SendPropertyChanging();
			entity.Capacitacion_modulo = this;
		}
		
		private void detach_capacitacion_modulos_vendedores(capacitacion_modulos_vendedore entity)
		{
			this.SendPropertyChanging();
			entity.Capacitacion_modulo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.capacitacion_modulos_vendedores")]
	public partial class capacitacion_modulos_vendedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_capacitacion;
		
		private decimal _id_modulo;
		
		private string _vendedor;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private EntityRef<Capacitacion_modulo> _Capacitacion_modulo;
		
		private EntityRef<vendedore> _vendedore;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_capacitacionChanging(decimal value);
    partial void Onid_capacitacionChanged();
    partial void Onid_moduloChanging(decimal value);
    partial void Onid_moduloChanged();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    #endregion
		
		public capacitacion_modulos_vendedore()
		{
			this._Capacitacion_modulo = default(EntityRef<Capacitacion_modulo>);
			this._vendedore = default(EntityRef<vendedore>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_capacitacion", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_capacitacion
		{
			get
			{
				return this._id_capacitacion;
			}
			set
			{
				if ((this._id_capacitacion != value))
				{
					if (this._Capacitacion_modulo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_capacitacionChanging(value);
					this.SendPropertyChanging();
					this._id_capacitacion = value;
					this.SendPropertyChanged("id_capacitacion");
					this.Onid_capacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_modulo", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_modulo
		{
			get
			{
				return this._id_modulo;
			}
			set
			{
				if ((this._id_modulo != value))
				{
					if (this._Capacitacion_modulo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_moduloChanging(value);
					this.SendPropertyChanging();
					this._id_modulo = value;
					this.SendPropertyChanged("id_modulo");
					this.Onid_moduloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					if (this._vendedore.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Capacitacion_modulo_capacitacion_modulos_vendedore", Storage="_Capacitacion_modulo", ThisKey="id_capacitacion,id_modulo", OtherKey="id_capacitacion,id_modulo", IsForeignKey=true)]
		public Capacitacion_modulo Capacitacion_modulo
		{
			get
			{
				return this._Capacitacion_modulo.Entity;
			}
			set
			{
				Capacitacion_modulo previousValue = this._Capacitacion_modulo.Entity;
				if (((previousValue != value) 
							|| (this._Capacitacion_modulo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Capacitacion_modulo.Entity = null;
						previousValue.capacitacion_modulos_vendedores.Remove(this);
					}
					this._Capacitacion_modulo.Entity = value;
					if ((value != null))
					{
						value.capacitacion_modulos_vendedores.Add(this);
						this._id_capacitacion = value.id_capacitacion;
						this._id_modulo = value.id_modulo;
					}
					else
					{
						this._id_capacitacion = default(decimal);
						this._id_modulo = default(decimal);
					}
					this.SendPropertyChanged("Capacitacion_modulo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vendedore_capacitacion_modulos_vendedore", Storage="_vendedore", ThisKey="vendedor", OtherKey="vendedor", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public vendedore vendedore
		{
			get
			{
				return this._vendedore.Entity;
			}
			set
			{
				vendedore previousValue = this._vendedore.Entity;
				if (((previousValue != value) 
							|| (this._vendedore.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._vendedore.Entity = null;
						previousValue.capacitacion_modulos_vendedores.Remove(this);
					}
					this._vendedore.Entity = value;
					if ((value != null))
					{
						value.capacitacion_modulos_vendedores.Add(this);
						this._vendedor = value.vendedor;
					}
					else
					{
						this._vendedor = default(string);
					}
					this.SendPropertyChanged("vendedore");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vendedores")]
	public partial class vendedore : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _vendedor;
		
		private System.Nullable<decimal> _compania;
		
		private System.Nullable<decimal> _num_contrato;
		
		private string _tipo_de_identificacion;
		
		private string _identificacion;
		
		private string _nombre;
		
		private string _apellido_01;
		
		private string _apellido_02;
		
		private string _telefono;
		
		private string _telefono_02;
		
		private string _telefono_03;
		
		private string _descuento;
		
		private string _descripcion;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _modificado_por;
		
		private System.Nullable<System.DateTime> _modificado_el;
		
		private string _zona;
		
		private System.Nullable<decimal> _provincia;
		
		private System.Nullable<decimal> _canton;
		
		private System.Nullable<decimal> _distrito;
		
		private System.Nullable<System.DateTime> _fecha_ingreso;
		
		private string _observacion;
		
		private System.Nullable<decimal> _estado;
		
		private int _mostrar_obs_fact;
		
		private decimal _venta_actual;
		
		private string _promotor_asignado;
		
		private string _patrocinador;
		
		private string _fax;
		
		private string _correo;
		
		private System.Nullable<decimal> _cierre_ingreso;
		
		private System.Nullable<decimal> _cierre_primer_venta;
		
		private System.Nullable<decimal> _nivel02;
		
		private string _cod_cliente;
		
		private System.Nullable<decimal> _PlanMercadeoActual;
		
		private System.Nullable<decimal> _gerente;
		
		private System.Nullable<decimal> _Ventas_totales;
		
		private System.Nullable<short> _incentivo_inicial;
		
		private string _referencia_incentivo;
		
		private string _referencia_primer_venta;
		
		private System.Nullable<System.DateTime> _fecha_nacimiento;
		
		private System.Nullable<System.DateTime> _referencia_ingreso;
		
		private System.Nullable<decimal> _cierre_manager_01;
		
		private System.Nullable<decimal> _cierre_manager_02;
		
		private System.Nullable<decimal> _cierre_manager_03;
		
		private string _nombre_cuenta;
		
		private System.Nullable<decimal> _activo;
		
		private System.Nullable<System.DateTime> _fecha_inactivo;
		
		private System.Nullable<decimal> _zona_ventas;
		
		private System.Nullable<decimal> _calificacion_ventas;
		
		private string _celular;
		
		private System.Nullable<decimal> _cierre_ejecutivo_ventas;
		
		private System.Nullable<System.DateTime> _fecha_ult_venta;
		
		private System.Nullable<decimal> _estado_seguimiento;
		
		private System.Nullable<int> _wsUpdate;
		
		private System.Nullable<int> _wsInsert;
		
		private EntitySet<capacitacion_modulos_vendedore> _capacitacion_modulos_vendedores;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void OncompaniaChanging(System.Nullable<decimal> value);
    partial void OncompaniaChanged();
    partial void Onnum_contratoChanging(System.Nullable<decimal> value);
    partial void Onnum_contratoChanged();
    partial void Ontipo_de_identificacionChanging(string value);
    partial void Ontipo_de_identificacionChanged();
    partial void OnidentificacionChanging(string value);
    partial void OnidentificacionChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void Onapellido_01Changing(string value);
    partial void Onapellido_01Changed();
    partial void Onapellido_02Changing(string value);
    partial void Onapellido_02Changed();
    partial void OntelefonoChanging(string value);
    partial void OntelefonoChanged();
    partial void Ontelefono_02Changing(string value);
    partial void Ontelefono_02Changed();
    partial void Ontelefono_03Changing(string value);
    partial void Ontelefono_03Changed();
    partial void OndescuentoChanging(string value);
    partial void OndescuentoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Onmodificado_porChanging(string value);
    partial void Onmodificado_porChanged();
    partial void Onmodificado_elChanging(System.Nullable<System.DateTime> value);
    partial void Onmodificado_elChanged();
    partial void OnzonaChanging(string value);
    partial void OnzonaChanged();
    partial void OnprovinciaChanging(System.Nullable<decimal> value);
    partial void OnprovinciaChanged();
    partial void OncantonChanging(System.Nullable<decimal> value);
    partial void OncantonChanged();
    partial void OndistritoChanging(System.Nullable<decimal> value);
    partial void OndistritoChanged();
    partial void Onfecha_ingresoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ingresoChanged();
    partial void OnobservacionChanging(string value);
    partial void OnobservacionChanged();
    partial void OnestadoChanging(System.Nullable<decimal> value);
    partial void OnestadoChanged();
    partial void Onmostrar_obs_factChanging(int value);
    partial void Onmostrar_obs_factChanged();
    partial void Onventa_actualChanging(decimal value);
    partial void Onventa_actualChanged();
    partial void Onpromotor_asignadoChanging(string value);
    partial void Onpromotor_asignadoChanged();
    partial void OnpatrocinadorChanging(string value);
    partial void OnpatrocinadorChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void Oncierre_ingresoChanging(System.Nullable<decimal> value);
    partial void Oncierre_ingresoChanged();
    partial void Oncierre_primer_ventaChanging(System.Nullable<decimal> value);
    partial void Oncierre_primer_ventaChanged();
    partial void Onnivel02Changing(System.Nullable<decimal> value);
    partial void Onnivel02Changed();
    partial void Oncod_clienteChanging(string value);
    partial void Oncod_clienteChanged();
    partial void OnPlanMercadeoActualChanging(System.Nullable<decimal> value);
    partial void OnPlanMercadeoActualChanged();
    partial void OngerenteChanging(System.Nullable<decimal> value);
    partial void OngerenteChanged();
    partial void OnVentas_totalesChanging(System.Nullable<decimal> value);
    partial void OnVentas_totalesChanged();
    partial void Onincentivo_inicialChanging(System.Nullable<short> value);
    partial void Onincentivo_inicialChanged();
    partial void Onreferencia_incentivoChanging(string value);
    partial void Onreferencia_incentivoChanged();
    partial void Onreferencia_primer_ventaChanging(string value);
    partial void Onreferencia_primer_ventaChanged();
    partial void Onfecha_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_nacimientoChanged();
    partial void Onreferencia_ingresoChanging(System.Nullable<System.DateTime> value);
    partial void Onreferencia_ingresoChanged();
    partial void Oncierre_manager_01Changing(System.Nullable<decimal> value);
    partial void Oncierre_manager_01Changed();
    partial void Oncierre_manager_02Changing(System.Nullable<decimal> value);
    partial void Oncierre_manager_02Changed();
    partial void Oncierre_manager_03Changing(System.Nullable<decimal> value);
    partial void Oncierre_manager_03Changed();
    partial void Onnombre_cuentaChanging(string value);
    partial void Onnombre_cuentaChanged();
    partial void OnactivoChanging(System.Nullable<decimal> value);
    partial void OnactivoChanged();
    partial void Onfecha_inactivoChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_inactivoChanged();
    partial void Onzona_ventasChanging(System.Nullable<decimal> value);
    partial void Onzona_ventasChanged();
    partial void Oncalificacion_ventasChanging(System.Nullable<decimal> value);
    partial void Oncalificacion_ventasChanged();
    partial void OncelularChanging(string value);
    partial void OncelularChanged();
    partial void Oncierre_ejecutivo_ventasChanging(System.Nullable<decimal> value);
    partial void Oncierre_ejecutivo_ventasChanged();
    partial void Onfecha_ult_ventaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_ult_ventaChanged();
    partial void Onestado_seguimientoChanging(System.Nullable<decimal> value);
    partial void Onestado_seguimientoChanged();
    partial void OnwsUpdateChanging(System.Nullable<int> value);
    partial void OnwsUpdateChanged();
    partial void OnwsInsertChanging(System.Nullable<int> value);
    partial void OnwsInsertChanged();
    #endregion
		
		public vendedore()
		{
			this._capacitacion_modulos_vendedores = new EntitySet<capacitacion_modulos_vendedore>(new Action<capacitacion_modulos_vendedore>(this.attach_capacitacion_modulos_vendedores), new Action<capacitacion_modulos_vendedore>(this.detach_capacitacion_modulos_vendedores));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compania", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> compania
		{
			get
			{
				return this._compania;
			}
			set
			{
				if ((this._compania != value))
				{
					this.OncompaniaChanging(value);
					this.SendPropertyChanging();
					this._compania = value;
					this.SendPropertyChanged("compania");
					this.OncompaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_num_contrato", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> num_contrato
		{
			get
			{
				return this._num_contrato;
			}
			set
			{
				if ((this._num_contrato != value))
				{
					this.Onnum_contratoChanging(value);
					this.SendPropertyChanging();
					this._num_contrato = value;
					this.SendPropertyChanged("num_contrato");
					this.Onnum_contratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_de_identificacion", DbType="VarChar(255)")]
		public string tipo_de_identificacion
		{
			get
			{
				return this._tipo_de_identificacion;
			}
			set
			{
				if ((this._tipo_de_identificacion != value))
				{
					this.Ontipo_de_identificacionChanging(value);
					this.SendPropertyChanging();
					this._tipo_de_identificacion = value;
					this.SendPropertyChanged("tipo_de_identificacion");
					this.Ontipo_de_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identificacion", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string identificacion
		{
			get
			{
				return this._identificacion;
			}
			set
			{
				if ((this._identificacion != value))
				{
					this.OnidentificacionChanging(value);
					this.SendPropertyChanging();
					this._identificacion = value;
					this.SendPropertyChanged("identificacion");
					this.OnidentificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_01", DbType="VarChar(255)")]
		public string apellido_01
		{
			get
			{
				return this._apellido_01;
			}
			set
			{
				if ((this._apellido_01 != value))
				{
					this.Onapellido_01Changing(value);
					this.SendPropertyChanging();
					this._apellido_01 = value;
					this.SendPropertyChanged("apellido_01");
					this.Onapellido_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido_02", DbType="VarChar(255)")]
		public string apellido_02
		{
			get
			{
				return this._apellido_02;
			}
			set
			{
				if ((this._apellido_02 != value))
				{
					this.Onapellido_02Changing(value);
					this.SendPropertyChanging();
					this._apellido_02 = value;
					this.SendPropertyChanged("apellido_02");
					this.Onapellido_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="VarChar(50)")]
		public string telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_02", DbType="VarChar(50)")]
		public string telefono_02
		{
			get
			{
				return this._telefono_02;
			}
			set
			{
				if ((this._telefono_02 != value))
				{
					this.Ontelefono_02Changing(value);
					this.SendPropertyChanging();
					this._telefono_02 = value;
					this.SendPropertyChanged("telefono_02");
					this.Ontelefono_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono_03", DbType="VarChar(50)")]
		public string telefono_03
		{
			get
			{
				return this._telefono_03;
			}
			set
			{
				if ((this._telefono_03 != value))
				{
					this.Ontelefono_03Changing(value);
					this.SendPropertyChanging();
					this._telefono_03 = value;
					this.SendPropertyChanged("telefono_03");
					this.Ontelefono_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descuento", DbType="VarChar(255)")]
		public string descuento
		{
			get
			{
				return this._descuento;
			}
			set
			{
				if ((this._descuento != value))
				{
					this.OndescuentoChanging(value);
					this.SendPropertyChanging();
					this._descuento = value;
					this.SendPropertyChanged("descuento");
					this.OndescuentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(255)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(255)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_por", DbType="VarChar(255)")]
		public string modificado_por
		{
			get
			{
				return this._modificado_por;
			}
			set
			{
				if ((this._modificado_por != value))
				{
					this.Onmodificado_porChanging(value);
					this.SendPropertyChanging();
					this._modificado_por = value;
					this.SendPropertyChanged("modificado_por");
					this.Onmodificado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificado_el
		{
			get
			{
				return this._modificado_el;
			}
			set
			{
				if ((this._modificado_el != value))
				{
					this.Onmodificado_elChanging(value);
					this.SendPropertyChanging();
					this._modificado_el = value;
					this.SendPropertyChanged("modificado_el");
					this.Onmodificado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona", DbType="VarChar(16)")]
		public string zona
		{
			get
			{
				return this._zona;
			}
			set
			{
				if ((this._zona != value))
				{
					this.OnzonaChanging(value);
					this.SendPropertyChanging();
					this._zona = value;
					this.SendPropertyChanged("zona");
					this.OnzonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_provincia", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> provincia
		{
			get
			{
				return this._provincia;
			}
			set
			{
				if ((this._provincia != value))
				{
					this.OnprovinciaChanging(value);
					this.SendPropertyChanging();
					this._provincia = value;
					this.SendPropertyChanged("provincia");
					this.OnprovinciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canton", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> canton
		{
			get
			{
				return this._canton;
			}
			set
			{
				if ((this._canton != value))
				{
					this.OncantonChanging(value);
					this.SendPropertyChanging();
					this._canton = value;
					this.SendPropertyChanged("canton");
					this.OncantonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_distrito", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> distrito
		{
			get
			{
				return this._distrito;
			}
			set
			{
				if ((this._distrito != value))
				{
					this.OndistritoChanging(value);
					this.SendPropertyChanging();
					this._distrito = value;
					this.SendPropertyChanged("distrito");
					this.OndistritoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ingreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_ingreso
		{
			get
			{
				return this._fecha_ingreso;
			}
			set
			{
				if ((this._fecha_ingreso != value))
				{
					this.Onfecha_ingresoChanging(value);
					this.SendPropertyChanging();
					this._fecha_ingreso = value;
					this.SendPropertyChanged("fecha_ingreso");
					this.Onfecha_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_observacion", DbType="VarChar(255)")]
		public string observacion
		{
			get
			{
				return this._observacion;
			}
			set
			{
				if ((this._observacion != value))
				{
					this.OnobservacionChanging(value);
					this.SendPropertyChanging();
					this._observacion = value;
					this.SendPropertyChanged("observacion");
					this.OnobservacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mostrar_obs_fact", DbType="Int NOT NULL")]
		public int mostrar_obs_fact
		{
			get
			{
				return this._mostrar_obs_fact;
			}
			set
			{
				if ((this._mostrar_obs_fact != value))
				{
					this.Onmostrar_obs_factChanging(value);
					this.SendPropertyChanging();
					this._mostrar_obs_fact = value;
					this.SendPropertyChanged("mostrar_obs_fact");
					this.Onmostrar_obs_factChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_venta_actual", DbType="Money NOT NULL")]
		public decimal venta_actual
		{
			get
			{
				return this._venta_actual;
			}
			set
			{
				if ((this._venta_actual != value))
				{
					this.Onventa_actualChanging(value);
					this.SendPropertyChanging();
					this._venta_actual = value;
					this.SendPropertyChanged("venta_actual");
					this.Onventa_actualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_promotor_asignado", DbType="VarChar(50)")]
		public string promotor_asignado
		{
			get
			{
				return this._promotor_asignado;
			}
			set
			{
				if ((this._promotor_asignado != value))
				{
					this.Onpromotor_asignadoChanging(value);
					this.SendPropertyChanging();
					this._promotor_asignado = value;
					this.SendPropertyChanged("promotor_asignado");
					this.Onpromotor_asignadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patrocinador", DbType="VarChar(50)")]
		public string patrocinador
		{
			get
			{
				return this._patrocinador;
			}
			set
			{
				if ((this._patrocinador != value))
				{
					this.OnpatrocinadorChanging(value);
					this.SendPropertyChanging();
					this._patrocinador = value;
					this.SendPropertyChanged("patrocinador");
					this.OnpatrocinadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(200)")]
		public string fax
		{
			get
			{
				return this._fax;
			}
			set
			{
				if ((this._fax != value))
				{
					this.OnfaxChanging(value);
					this.SendPropertyChanging();
					this._fax = value;
					this.SendPropertyChanged("fax");
					this.OnfaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(200)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_ingreso", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_ingreso
		{
			get
			{
				return this._cierre_ingreso;
			}
			set
			{
				if ((this._cierre_ingreso != value))
				{
					this.Oncierre_ingresoChanging(value);
					this.SendPropertyChanging();
					this._cierre_ingreso = value;
					this.SendPropertyChanged("cierre_ingreso");
					this.Oncierre_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_primer_venta", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_primer_venta
		{
			get
			{
				return this._cierre_primer_venta;
			}
			set
			{
				if ((this._cierre_primer_venta != value))
				{
					this.Oncierre_primer_ventaChanging(value);
					this.SendPropertyChanging();
					this._cierre_primer_venta = value;
					this.SendPropertyChanged("cierre_primer_venta");
					this.Oncierre_primer_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel02", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> nivel02
		{
			get
			{
				return this._nivel02;
			}
			set
			{
				if ((this._nivel02 != value))
				{
					this.Onnivel02Changing(value);
					this.SendPropertyChanging();
					this._nivel02 = value;
					this.SendPropertyChanged("nivel02");
					this.Onnivel02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cod_cliente", DbType="VarChar(50)")]
		public string cod_cliente
		{
			get
			{
				return this._cod_cliente;
			}
			set
			{
				if ((this._cod_cliente != value))
				{
					this.Oncod_clienteChanging(value);
					this.SendPropertyChanging();
					this._cod_cliente = value;
					this.SendPropertyChanged("cod_cliente");
					this.Oncod_clienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PlanMercadeoActual", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> PlanMercadeoActual
		{
			get
			{
				return this._PlanMercadeoActual;
			}
			set
			{
				if ((this._PlanMercadeoActual != value))
				{
					this.OnPlanMercadeoActualChanging(value);
					this.SendPropertyChanging();
					this._PlanMercadeoActual = value;
					this.SendPropertyChanged("PlanMercadeoActual");
					this.OnPlanMercadeoActualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gerente", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> gerente
		{
			get
			{
				return this._gerente;
			}
			set
			{
				if ((this._gerente != value))
				{
					this.OngerenteChanging(value);
					this.SendPropertyChanging();
					this._gerente = value;
					this.SendPropertyChanged("gerente");
					this.OngerenteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ventas_totales", DbType="Money")]
		public System.Nullable<decimal> Ventas_totales
		{
			get
			{
				return this._Ventas_totales;
			}
			set
			{
				if ((this._Ventas_totales != value))
				{
					this.OnVentas_totalesChanging(value);
					this.SendPropertyChanging();
					this._Ventas_totales = value;
					this.SendPropertyChanged("Ventas_totales");
					this.OnVentas_totalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_incentivo_inicial", DbType="SmallInt")]
		public System.Nullable<short> incentivo_inicial
		{
			get
			{
				return this._incentivo_inicial;
			}
			set
			{
				if ((this._incentivo_inicial != value))
				{
					this.Onincentivo_inicialChanging(value);
					this.SendPropertyChanging();
					this._incentivo_inicial = value;
					this.SendPropertyChanged("incentivo_inicial");
					this.Onincentivo_inicialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_incentivo", DbType="VarChar(16)")]
		public string referencia_incentivo
		{
			get
			{
				return this._referencia_incentivo;
			}
			set
			{
				if ((this._referencia_incentivo != value))
				{
					this.Onreferencia_incentivoChanging(value);
					this.SendPropertyChanging();
					this._referencia_incentivo = value;
					this.SendPropertyChanged("referencia_incentivo");
					this.Onreferencia_incentivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_primer_venta", DbType="VarChar(50)")]
		public string referencia_primer_venta
		{
			get
			{
				return this._referencia_primer_venta;
			}
			set
			{
				if ((this._referencia_primer_venta != value))
				{
					this.Onreferencia_primer_ventaChanging(value);
					this.SendPropertyChanging();
					this._referencia_primer_venta = value;
					this.SendPropertyChanged("referencia_primer_venta");
					this.Onreferencia_primer_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencia_ingreso", DbType="DateTime")]
		public System.Nullable<System.DateTime> referencia_ingreso
		{
			get
			{
				return this._referencia_ingreso;
			}
			set
			{
				if ((this._referencia_ingreso != value))
				{
					this.Onreferencia_ingresoChanging(value);
					this.SendPropertyChanging();
					this._referencia_ingreso = value;
					this.SendPropertyChanged("referencia_ingreso");
					this.Onreferencia_ingresoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_manager_01", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_manager_01
		{
			get
			{
				return this._cierre_manager_01;
			}
			set
			{
				if ((this._cierre_manager_01 != value))
				{
					this.Oncierre_manager_01Changing(value);
					this.SendPropertyChanging();
					this._cierre_manager_01 = value;
					this.SendPropertyChanged("cierre_manager_01");
					this.Oncierre_manager_01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_manager_02", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_manager_02
		{
			get
			{
				return this._cierre_manager_02;
			}
			set
			{
				if ((this._cierre_manager_02 != value))
				{
					this.Oncierre_manager_02Changing(value);
					this.SendPropertyChanging();
					this._cierre_manager_02 = value;
					this.SendPropertyChanged("cierre_manager_02");
					this.Oncierre_manager_02Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_manager_03", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_manager_03
		{
			get
			{
				return this._cierre_manager_03;
			}
			set
			{
				if ((this._cierre_manager_03 != value))
				{
					this.Oncierre_manager_03Changing(value);
					this.SendPropertyChanging();
					this._cierre_manager_03 = value;
					this.SendPropertyChanged("cierre_manager_03");
					this.Oncierre_manager_03Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_cuenta", DbType="VarChar(200)")]
		public string nombre_cuenta
		{
			get
			{
				return this._nombre_cuenta;
			}
			set
			{
				if ((this._nombre_cuenta != value))
				{
					this.Onnombre_cuentaChanging(value);
					this.SendPropertyChanging();
					this._nombre_cuenta = value;
					this.SendPropertyChanged("nombre_cuenta");
					this.Onnombre_cuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_inactivo", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_inactivo
		{
			get
			{
				return this._fecha_inactivo;
			}
			set
			{
				if ((this._fecha_inactivo != value))
				{
					this.Onfecha_inactivoChanging(value);
					this.SendPropertyChanging();
					this._fecha_inactivo = value;
					this.SendPropertyChanged("fecha_inactivo");
					this.Onfecha_inactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zona_ventas", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> zona_ventas
		{
			get
			{
				return this._zona_ventas;
			}
			set
			{
				if ((this._zona_ventas != value))
				{
					this.Onzona_ventasChanging(value);
					this.SendPropertyChanging();
					this._zona_ventas = value;
					this.SendPropertyChanged("zona_ventas");
					this.Onzona_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_calificacion_ventas", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> calificacion_ventas
		{
			get
			{
				return this._calificacion_ventas;
			}
			set
			{
				if ((this._calificacion_ventas != value))
				{
					this.Oncalificacion_ventasChanging(value);
					this.SendPropertyChanging();
					this._calificacion_ventas = value;
					this.SendPropertyChanged("calificacion_ventas");
					this.Oncalificacion_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="VarChar(30)")]
		public string celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_ejecutivo_ventas", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_ejecutivo_ventas
		{
			get
			{
				return this._cierre_ejecutivo_ventas;
			}
			set
			{
				if ((this._cierre_ejecutivo_ventas != value))
				{
					this.Oncierre_ejecutivo_ventasChanging(value);
					this.SendPropertyChanging();
					this._cierre_ejecutivo_ventas = value;
					this.SendPropertyChanged("cierre_ejecutivo_ventas");
					this.Oncierre_ejecutivo_ventasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_ult_venta", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha_ult_venta
		{
			get
			{
				return this._fecha_ult_venta;
			}
			set
			{
				if ((this._fecha_ult_venta != value))
				{
					this.Onfecha_ult_ventaChanging(value);
					this.SendPropertyChanging();
					this._fecha_ult_venta = value;
					this.SendPropertyChanged("fecha_ult_venta");
					this.Onfecha_ult_ventaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_seguimiento", DbType="Decimal(3,0)")]
		public System.Nullable<decimal> estado_seguimiento
		{
			get
			{
				return this._estado_seguimiento;
			}
			set
			{
				if ((this._estado_seguimiento != value))
				{
					this.Onestado_seguimientoChanging(value);
					this.SendPropertyChanging();
					this._estado_seguimiento = value;
					this.SendPropertyChanged("estado_seguimiento");
					this.Onestado_seguimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wsUpdate", DbType="Int")]
		public System.Nullable<int> wsUpdate
		{
			get
			{
				return this._wsUpdate;
			}
			set
			{
				if ((this._wsUpdate != value))
				{
					this.OnwsUpdateChanging(value);
					this.SendPropertyChanging();
					this._wsUpdate = value;
					this.SendPropertyChanged("wsUpdate");
					this.OnwsUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wsInsert", DbType="Int")]
		public System.Nullable<int> wsInsert
		{
			get
			{
				return this._wsInsert;
			}
			set
			{
				if ((this._wsInsert != value))
				{
					this.OnwsInsertChanging(value);
					this.SendPropertyChanging();
					this._wsInsert = value;
					this.SendPropertyChanged("wsInsert");
					this.OnwsInsertChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vendedore_capacitacion_modulos_vendedore", Storage="_capacitacion_modulos_vendedores", ThisKey="vendedor", OtherKey="vendedor")]
		public EntitySet<capacitacion_modulos_vendedore> capacitacion_modulos_vendedores
		{
			get
			{
				return this._capacitacion_modulos_vendedores;
			}
			set
			{
				this._capacitacion_modulos_vendedores.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_capacitacion_modulos_vendedores(capacitacion_modulos_vendedore entity)
		{
			this.SendPropertyChanging();
			entity.vendedore = this;
		}
		
		private void detach_capacitacion_modulos_vendedores(capacitacion_modulos_vendedore entity)
		{
			this.SendPropertyChanging();
			entity.vendedore = null;
		}
	}
}
#pragma warning restore 1591
