<?xml version="1.0" encoding="utf-8"?><Database Name="Sakif" Class="DataMapDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.0.2;Initial Catalog=Sakif;User ID=sa" SettingsObjectName="Academic.DataAccess.Properties.Settings" SettingsPropertyName="SakifConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Capacitaciones" Member="Capacitacions">
    <Type Name="Capacitacion">
      <Column Name="id" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Capacitacion_Capacitacion_modulo" Member="Capacitacion_modulos" ThisKey="id" OtherKey="id_capacitacion" Type="Capacitacion_modulo" />
    </Type>
  </Table>
  <Table Name="dbo.Capacitacion_modulos" Member="Capacitacion_modulos">
    <Type Name="Capacitacion_modulo">
      <Column Name="id_capacitacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_modulo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="prioridad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Association Name="Capacitacion_modulo_capacitacion_modulos_vendedore" Member="capacitacion_modulos_vendedores" ThisKey="id_capacitacion,id_modulo" OtherKey="id_capacitacion,id_modulo" Type="capacitacion_modulos_vendedore" />
      <Association Name="Capacitacion_Capacitacion_modulo" Member="Capacitacion" ThisKey="id_capacitacion" OtherKey="id" Type="Capacitacion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.capacitacion_modulos_vendedores" Member="capacitacion_modulos_vendedores">
    <Type Name="capacitacion_modulos_vendedore">
      <Column Name="id_capacitacion" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_modulo" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="vendedor" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Capacitacion_modulo_capacitacion_modulos_vendedore" Member="Capacitacion_modulo" ThisKey="id_capacitacion,id_modulo" OtherKey="id_capacitacion,id_modulo" Type="Capacitacion_modulo" IsForeignKey="true" />
      <Association Name="vendedore_capacitacion_modulos_vendedore" Member="vendedore" ThisKey="vendedor" OtherKey="vendedor" Type="vendedore" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.vendedores" Member="vendedores">
    <Type Name="vendedore">
      <Column Name="vendedor" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="compania" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="num_contrato" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="tipo_de_identificacion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="identificacion" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="apellido_01" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="apellido_02" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono_02" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="telefono_03" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="descuento" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="creado_por" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="creado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="modificado_por" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="modificado_el" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="zona" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="provincia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="canton" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="distrito" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_ingreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="observacion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="estado" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="mostrar_obs_fact" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="venta_actual" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="promotor_asignado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="patrocinador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="correo" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cierre_ingreso" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cierre_primer_venta" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="nivel02" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cod_cliente" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PlanMercadeoActual" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="gerente" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Ventas_totales" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="incentivo_inicial" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="referencia_incentivo" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="referencia_primer_venta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_nacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="referencia_ingreso" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cierre_manager_01" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cierre_manager_02" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="cierre_manager_03" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="nombre_cuenta" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="activo" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_inactivo" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="zona_ventas" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="calificacion_ventas" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="celular" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="cierre_ejecutivo_ventas" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_ult_venta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="estado_seguimiento" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="wsUpdate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="wsInsert" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="vendedore_capacitacion_modulos_vendedore" Member="capacitacion_modulos_vendedores" ThisKey="vendedor" OtherKey="vendedor" Type="capacitacion_modulos_vendedore" />
    </Type>
  </Table>
</Database>