#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CirculosExcelencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sakif")]
	public partial class DataBaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCirculoExcelencia(CirculoExcelencia instance);
    partial void UpdateCirculoExcelencia(CirculoExcelencia instance);
    partial void DeleteCirculoExcelencia(CirculoExcelencia instance);
    partial void InsertNivelCirculo(NivelCirculo instance);
    partial void UpdateNivelCirculo(NivelCirculo instance);
    partial void DeleteNivelCirculo(NivelCirculo instance);
    #endregion
		
		public DataBaseDataContext() : 
				base(global::CirculosExcelencia.Properties.Settings.Default.SakifConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataBaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CirculoExcelencia> CirculoExcelencias
		{
			get
			{
				return this.GetTable<CirculoExcelencia>();
			}
		}
		
		public System.Data.Linq.Table<NivelCirculo> NivelCirculos
		{
			get
			{
				return this.GetTable<NivelCirculo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.circulos_excelencia")]
	public partial class CirculoExcelencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _id_circulo;
		
		private string _vendedor;
		
		private int _tipo;
		
		private decimal _id_nivel;
		
		private decimal _cierre_inicio;
		
		private System.Nullable<decimal> _cierre_final;
		
		private System.Nullable<decimal> _estado;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _creado_por;
		
		private System.Nullable<System.DateTime> _modificado_el;
		
		private string _modificado_por;
		
		private EntityRef<NivelCirculo> _NivelCirculo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_circuloChanging(decimal value);
    partial void Onid_circuloChanged();
    partial void OnvendedorChanging(string value);
    partial void OnvendedorChanged();
    partial void OntipoChanging(int value);
    partial void OntipoChanged();
    partial void Onid_nivelChanging(decimal value);
    partial void Onid_nivelChanged();
    partial void Oncierre_inicioChanging(decimal value);
    partial void Oncierre_inicioChanged();
    partial void Oncierre_finalChanging(System.Nullable<decimal> value);
    partial void Oncierre_finalChanged();
    partial void OnestadoChanging(System.Nullable<decimal> value);
    partial void OnestadoChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    partial void Onmodificado_elChanging(System.Nullable<System.DateTime> value);
    partial void Onmodificado_elChanged();
    partial void Onmodificado_porChanging(string value);
    partial void Onmodificado_porChanged();
    #endregion
		
		public CirculoExcelencia()
		{
			this._NivelCirculo = default(EntityRef<NivelCirculo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_circulo", AutoSync=AutoSync.Always, DbType="Decimal(18,0) NOT NULL IDENTITY", IsDbGenerated=true)]
		public decimal id_circulo
		{
			get
			{
				return this._id_circulo;
			}
			set
			{
				if ((this._id_circulo != value))
				{
					this.Onid_circuloChanging(value);
					this.SendPropertyChanging();
					this._id_circulo = value;
					this.SendPropertyChanged("id_circulo");
					this.Onid_circuloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendedor", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string vendedor
		{
			get
			{
				return this._vendedor;
			}
			set
			{
				if ((this._vendedor != value))
				{
					this.OnvendedorChanging(value);
					this.SendPropertyChanging();
					this._vendedor = value;
					this.SendPropertyChanged("vendedor");
					this.OnvendedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					if (this._NivelCirculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nivel", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_nivel
		{
			get
			{
				return this._id_nivel;
			}
			set
			{
				if ((this._id_nivel != value))
				{
					if (this._NivelCirculo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nivelChanging(value);
					this.SendPropertyChanging();
					this._id_nivel = value;
					this.SendPropertyChanged("id_nivel");
					this.Onid_nivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_inicio", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal cierre_inicio
		{
			get
			{
				return this._cierre_inicio;
			}
			set
			{
				if ((this._cierre_inicio != value))
				{
					this.Oncierre_inicioChanging(value);
					this.SendPropertyChanging();
					this._cierre_inicio = value;
					this.SendPropertyChanged("cierre_inicio");
					this.Oncierre_inicioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cierre_final", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> cierre_final
		{
			get
			{
				return this._cierre_final;
			}
			set
			{
				if ((this._cierre_final != value))
				{
					this.Oncierre_finalChanging(value);
					this.SendPropertyChanging();
					this._cierre_final = value;
					this.SendPropertyChanged("cierre_final");
					this.Oncierre_finalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(50)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> modificado_el
		{
			get
			{
				return this._modificado_el;
			}
			set
			{
				if ((this._modificado_el != value))
				{
					this.Onmodificado_elChanging(value);
					this.SendPropertyChanging();
					this._modificado_el = value;
					this.SendPropertyChanged("modificado_el");
					this.Onmodificado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modificado_por", DbType="VarChar(50)")]
		public string modificado_por
		{
			get
			{
				return this._modificado_por;
			}
			set
			{
				if ((this._modificado_por != value))
				{
					this.Onmodificado_porChanging(value);
					this.SendPropertyChanging();
					this._modificado_por = value;
					this.SendPropertyChanged("modificado_por");
					this.Onmodificado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="niveles_circulo_excelencia_circulos_excelencia", Storage="_NivelCirculo", ThisKey="id_nivel,tipo", OtherKey="id_nivel,tipo", IsForeignKey=true)]
		public NivelCirculo NivelCirculo
		{
			get
			{
				return this._NivelCirculo.Entity;
			}
			set
			{
				NivelCirculo previousValue = this._NivelCirculo.Entity;
				if (((previousValue != value) 
							|| (this._NivelCirculo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NivelCirculo.Entity = null;
						previousValue.CirculoExcelencias.Remove(this);
					}
					this._NivelCirculo.Entity = value;
					if ((value != null))
					{
						value.CirculoExcelencias.Add(this);
						this._id_nivel = value.id_nivel;
						this._tipo = value.tipo;
					}
					else
					{
						this._id_nivel = default(decimal);
						this._tipo = default(int);
					}
					this.SendPropertyChanged("NivelCirculo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.niveles_circulo_excelencia")]
	public partial class NivelCirculo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private decimal _plan_mercadeo;
		
		private decimal _id_nivel;
		
		private int _tipo;
		
		private string _descripcion;
		
		private System.Nullable<decimal> _MontoNivel;
		
		private System.Nullable<decimal> _puntos;
		
		private System.Nullable<decimal> _meses_consecutivo;
		
		private System.Nullable<System.DateTime> _creado_el;
		
		private string _creado_por;
		
		private EntitySet<CirculoExcelencia> _CirculoExcelencias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplan_mercadeoChanging(decimal value);
    partial void Onplan_mercadeoChanged();
    partial void Onid_nivelChanging(decimal value);
    partial void Onid_nivelChanged();
    partial void OntipoChanging(int value);
    partial void OntipoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnMontoNivelChanging(System.Nullable<decimal> value);
    partial void OnMontoNivelChanged();
    partial void OnpuntosChanging(System.Nullable<decimal> value);
    partial void OnpuntosChanged();
    partial void Onmeses_consecutivoChanging(System.Nullable<decimal> value);
    partial void Onmeses_consecutivoChanged();
    partial void Oncreado_elChanging(System.Nullable<System.DateTime> value);
    partial void Oncreado_elChanged();
    partial void Oncreado_porChanging(string value);
    partial void Oncreado_porChanged();
    #endregion
		
		public NivelCirculo()
		{
			this._CirculoExcelencias = new EntitySet<CirculoExcelencia>(new Action<CirculoExcelencia>(this.attach_CirculoExcelencias), new Action<CirculoExcelencia>(this.detach_CirculoExcelencias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plan_mercadeo", DbType="Decimal(18,0) NOT NULL")]
		public decimal plan_mercadeo
		{
			get
			{
				return this._plan_mercadeo;
			}
			set
			{
				if ((this._plan_mercadeo != value))
				{
					this.Onplan_mercadeoChanging(value);
					this.SendPropertyChanging();
					this._plan_mercadeo = value;
					this.SendPropertyChanged("plan_mercadeo");
					this.Onplan_mercadeoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nivel", DbType="Decimal(18,0) NOT NULL", IsPrimaryKey=true)]
		public decimal id_nivel
		{
			get
			{
				return this._id_nivel;
			}
			set
			{
				if ((this._id_nivel != value))
				{
					this.Onid_nivelChanging(value);
					this.SendPropertyChanging();
					this._id_nivel = value;
					this.SendPropertyChanged("id_nivel");
					this.Onid_nivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(150)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoNivel", DbType="Money")]
		public System.Nullable<decimal> MontoNivel
		{
			get
			{
				return this._MontoNivel;
			}
			set
			{
				if ((this._MontoNivel != value))
				{
					this.OnMontoNivelChanging(value);
					this.SendPropertyChanging();
					this._MontoNivel = value;
					this.SendPropertyChanged("MontoNivel");
					this.OnMontoNivelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="Money")]
		public System.Nullable<decimal> puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_meses_consecutivo", DbType="Money")]
		public System.Nullable<decimal> meses_consecutivo
		{
			get
			{
				return this._meses_consecutivo;
			}
			set
			{
				if ((this._meses_consecutivo != value))
				{
					this.Onmeses_consecutivoChanging(value);
					this.SendPropertyChanging();
					this._meses_consecutivo = value;
					this.SendPropertyChanged("meses_consecutivo");
					this.Onmeses_consecutivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_el", DbType="DateTime")]
		public System.Nullable<System.DateTime> creado_el
		{
			get
			{
				return this._creado_el;
			}
			set
			{
				if ((this._creado_el != value))
				{
					this.Oncreado_elChanging(value);
					this.SendPropertyChanging();
					this._creado_el = value;
					this.SendPropertyChanged("creado_el");
					this.Oncreado_elChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creado_por", DbType="VarChar(50)")]
		public string creado_por
		{
			get
			{
				return this._creado_por;
			}
			set
			{
				if ((this._creado_por != value))
				{
					this.Oncreado_porChanging(value);
					this.SendPropertyChanging();
					this._creado_por = value;
					this.SendPropertyChanged("creado_por");
					this.Oncreado_porChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="niveles_circulo_excelencia_circulos_excelencia", Storage="_CirculoExcelencias", ThisKey="id_nivel,tipo", OtherKey="id_nivel,tipo")]
		public EntitySet<CirculoExcelencia> CirculoExcelencias
		{
			get
			{
				return this._CirculoExcelencias;
			}
			set
			{
				this._CirculoExcelencias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CirculoExcelencias(CirculoExcelencia entity)
		{
			this.SendPropertyChanging();
			entity.NivelCirculo = this;
		}
		
		private void detach_CirculoExcelencias(CirculoExcelencia entity)
		{
			this.SendPropertyChanging();
			entity.NivelCirculo = null;
		}
	}
}
#pragma warning restore 1591
